---
collections:
  # Install a collection from Ansible Galaxy.
  - name: ibm.ibm_zos_core
    version: "1.12.1"
    source: https://galaxy.ansible.com
  - name: ibm.ibm_zos_cics
    version: "1.0.6"
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
  - name: /var/lib/awx/projects/_8__genapp/ibm-ibm_zos_wazi_deploy-3.0.4.tar.gz
    type: file
