apiVersion: deploy.ibm.com/v1
kind: DeploymentState
metadata:
  name: cics-genapp
  description: cics-genapp
  version: 1.0.63
  annotations:
    creation_timestamp: 20241022.220641.143
manifests:
- name: cics-genapp
  description: cics-genapp
  version: 1.0.63
  annotations:
    creation_timestamp: 20241022.132618.720
    scm:
      type: git
      uri: git@github.com:jbyibm/cics-genapp.git
      branch: main
      short_commit: 81e8ab71
    package:
      name: sys-wazi-deploy-team/cics-genapp-wazideploy-dynamic-build
      properties:
      - key: repository_path
        value: wazideploy/dynamic/cics-genapp
      - key: repository
        value: sys-wazi-deploy-team-pentest-generic-local
      - key: build_name
        value: sys-wazi-deploy-team/cics-genapp-wazideploy-dynamic-build
      - key: build_number
        value: '47'
      uri: https://na.artifactory.swg-devops.com/ui/builds/sys-wazi-deploy-team%2Fcics-genapp-wazideploy-dynamic-build/47
      type: ARTIFACTORY
artifacts:
- name: LGIPDB01
  description: LGIPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092600
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 07af9532c5eb75e4be8b388000e5f519634f1d151544e729ec2d54691bf325f9
  state: UNDEFINED
- name: SSMAP
  description: SSMAP.MAPLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/SSMAP.MAPLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092548
  - key: wd_manifest_index
    value: 0
  type: MAPLOAD
  hash: 09afa05be2f4491c696151709e5d7b89ea40dbd2c1be888b46c6d7e5cc95abf7
  state: UNDEFINED
- name: LGICVS01
  description: LGICVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092559
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 0ab850b77f3a109b0ac77c29c83e32ac861b109fd627fdc4614c37da8d7242d8
  state: UNDEFINED
- name: LGACDB02
  description: LGACDB02.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB02.DBRM
  - key: fingerprint
    value: 1b0cfb8fd9c97d0ff036015947ff513b25a7f8c48a99437698762f7f649c45ae
  - key: wd_manifest_index
    value: 0
  type: DBRM
  hash: 1b0cfb8fd9c97d0ff036015947ff513b25a7f8c48a99437698762f7f649c45ae
  state: UNDEFINED
- name: LGDPDB01
  description: LGDPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092555
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 1d20022d3f815299f9729db0afe273e7eb36c00cb1c6ddc6ba8a4feeb1348a65
  state: UNDEFINED
- name: LGIPDB01
  description: LGIPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGIPDB01.DBRM
  - key: fingerprint
    value: 2b3da2f8c41b0a7d1c1d9a101947f09c8cf9604008945cb848171c63b806a121
  - key: wd_manifest_index
    value: 0
  type: DBRM
  hash: 2b3da2f8c41b0a7d1c1d9a101947f09c8cf9604008945cb848171c63b806a121
  state: UNDEFINED
- name: LGACUS01
  description: LGACUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092551
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 2e156e23affa3cb019fe733f1be571ce68122e945db9e6a5c7e13208c31d0b2c
  state: UNDEFINED
- name: LGUCDB01
  description: LGUCDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092603
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 3622a1c4fd9cfd8c8b2f8276b2028e18190e75ae3228a4c22d8c680b54431fd5
  state: UNDEFINED
- name: LGIPOL01
  description: LGIPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092600
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 415361cbd2970406ff0029b92413a908297a7ff5f252941e9f95a7127376d682
  state: UNDEFINED
- name: LGUPDB01
  description: LGUPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092606
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 48ec9ca6a3ef7f79c453398c6655b20d23535200a1fea637d829bfc07b7fa029
  state: UNDEFINED
- name: LGACDB01
  description: LGACDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB01.DBRM
  - key: fingerprint
    value: 52c750d9fdb28e58bea979e21e2b81e86c6cbed78baeef6b42d06c80467859b5
  - key: wd_manifest_index
    value: 0
  type: DBRM
  hash: 52c750d9fdb28e58bea979e21e2b81e86c6cbed78baeef6b42d06c80467859b5
  state: UNDEFINED
- name: HELLO2
  description: HELLO2.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO2.JCL
  - key: fingerprint
    value: 55e756a76e9339d24e5c6c46c102faf8ea468f7f2e49867f985a47e746529c1e
  - key: wd_manifest_index
    value: 0
  type: JCL
  hash: 55e756a76e9339d24e5c6c46c102faf8ea468f7f2e49867f985a47e746529c1e
  state: UNDEFINED
- name: HELLO1
  description: HELLO1.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO1.JCL
  - key: fingerprint
    value: 573a056000558d6ae6887bb816a8759c57cff8f23c09261e130250307f9e767a
  - key: wd_manifest_index
    value: 0
  type: JCL
  hash: 573a056000558d6ae6887bb816a8759c57cff8f23c09261e130250307f9e767a
  state: UNDEFINED
- name: LGICDB01
  description: LGICDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092557
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 57cb1431ef097406f8076bf0363bfda7c01880f58174c75027f8bdb0bfece935
  state: UNDEFINED
- name: LGUCVS01
  description: LGUCVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092605
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 662d279c422ba89e55ce2827b000e916b72c771841f704c6adfc176bc43c9a70
  state: UNDEFINED
- name: LGAPDB01
  description: LGAPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGAPDB01.DBRM
  - key: fingerprint
    value: 727e71dfb3d4763751bf86ca04decf0478e887e682a554e8bdf80f9a63e68a8a
  - key: wd_manifest_index
    value: 0
  type: DBRM
  hash: 727e71dfb3d4763751bf86ca04decf0478e887e682a554e8bdf80f9a63e68a8a
  state: UNDEFINED
- name: LGDPVS01
  description: LGDPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092556
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 72f36e47ef0a1eadf29fe6eb5c613295292500d0772128723728c1e3922fc57a
  state: UNDEFINED
- name: LGUPVS01
  description: LGUPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092607
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 75bb93906277d80b7ea104ed5a78e08f38af2e4801b96a5b2bd58ca02d005fde
  state: UNDEFINED
- name: LGUPDB01
  description: LGUPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUPDB01.DBRM
  - key: fingerprint
    value: 76b089b74e4203279b4cd547274e83f1a34957c220f55a214efe99aba92a58de
  - key: wd_manifest_index
    value: 0
  type: DBRM
  hash: 76b089b74e4203279b4cd547274e83f1a34957c220f55a214efe99aba92a58de
  state: UNDEFINED
- name: LGICUS01
  description: LGICUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092558
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 83c87e58626b194d3e76cb917c2663d182b732b25490fb9c5e23a01c8746bc5e
  state: UNDEFINED
- name: LGAPVS01
  description: LGAPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092554
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 8494460baf97f7511eac8a04bd983883b767eba9daadfd56f7f5cc5e0fbfbcc1
  state: UNDEFINED
- name: LGAPDB01
  description: LGAPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092553
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 84a58c95d93a106989b3fa93f385530d7c50e6baf7503db5dfd7e629e7e362e8
  state: UNDEFINED
- name: LGDPOL01
  description: LGDPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092556
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: 940b0e39e7a41722d08d03585efd18a2de6cea3c1546c8eb2114de5798f408ed
  state: UNDEFINED
- name: LGICDB01
  description: LGICDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGICDB01.DBRM
  - key: fingerprint
    value: 9ca39464c30e8565d6c3c4eadf0be9c0962780290ac7986a46ff2e2c1d9a170a
  - key: wd_manifest_index
    value: 0
  type: DBRM
  hash: 9ca39464c30e8565d6c3c4eadf0be9c0962780290ac7986a46ff2e2c1d9a170a
  state: UNDEFINED
- name: LGSTSQ
  description: LGSTSQ.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSTSQ.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092603
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: abcad4a7601479265fb80c3b531f7158905859f543c127c6ed06c67d595492be
  state: UNDEFINED
- name: ISPFSTAT
  description: ISPFSTAT.CEXEC
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.CEXEC/ISPFSTAT.CEXEC
  - key: fingerprint
    value: b67fc9819687a684956d9abb25c28362b397f12d786fc4876b4f234d95ad3b66
  - key: wd_manifest_index
    value: 0
  type: CEXEC
  hash: b67fc9819687a684956d9abb25c28362b397f12d786fc4876b4f234d95ad3b66
  state: UNDEFINED
- name: LGSETUP
  description: LGSETUP.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSETUP.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092602
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: b708617d34ef2eb16f3dacff8efa4c40d3f08dfc3c04a5f9863a9745b2321e37
  state: UNDEFINED
- name: LGACVS01
  description: LGACVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092552
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: b982f4735fb0add494ac0e8210e4786b8cc5a744e2bb4d6b0f173df87cc34f41
  state: UNDEFINED
- name: LGUCUS01
  description: LGUCUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092604
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: c5d6cf86142be52608d4af1c0e5e5e632c11f2e3a7207552d107e4463298226b
  state: UNDEFINED
- name: LGAPOL01
  description: LGAPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092553
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: cd9e95188459836a178d88cf8bfb740a0210f0c54bf9a228939a3e62e455d8eb
  state: UNDEFINED
- name: LGDPDB01
  description: LGDPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGDPDB01.DBRM
  - key: fingerprint
    value: db564582eed6d4355da78edd547677b9628760530b8d49e3dc2c8005e2b26cde
  - key: wd_manifest_index
    value: 0
  type: DBRM
  hash: db564582eed6d4355da78edd547677b9628760530b8d49e3dc2c8005e2b26cde
  state: UNDEFINED
- name: LGIPVS01
  description: LGIPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092601
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: e64e94dcdb1fe02964bad5ef555c1a2f487c0fef3c67c11b6f9974eb51067992
  state: UNDEFINED
- name: LGUCDB01
  description: LGUCDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUCDB01.DBRM
  - key: fingerprint
    value: e7a4dddef7d905a010044a4f81a13355c826fa6f76d640c7490729184677bf24
  - key: wd_manifest_index
    value: 0
  type: DBRM
  hash: e7a4dddef7d905a010044a4f81a13355c826fa6f76d640c7490729184677bf24
  state: UNDEFINED
- name: LGACDB01
  description: LGACDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092550
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: fa46def9f4fbfc5bc2a9b63d5815408a44ec2f0da5c20ae9fab939501f3132ef
  state: UNDEFINED
- name: LGACDB02
  description: LGACDB02.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB02.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092550
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: fa98b9e563099d0acb06e25f6e6d24a38a5d691a793ef1700de3d36505c185e9
  state: UNDEFINED
- name: LGUPOL01
  description: LGUPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024296092607
  - key: wd_manifest_index
    value: 0
  type: CICSLOAD
  hash: ff2bc4f5565198bd45a7c908b9c28a0483522c0ef41afd1e64d024bbc9d4f40e
  state: UNDEFINED
