#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- hosts: "{{ plum_hosts if plum_hosts is defined else 'all' }}"
  gather_facts: "{{ plum_gather_facts if plum_gather_facts is defined else 'no' }}"
  serial: "{{ plum_serial if plum_serial is defined else 5 }}"
  tasks:
      - name: Install PLUM
        ansible.builtin.pip:
          name: /runner/project/plum_py-0.9.1.tar.gz 
        delegate_to: localhost
        
      - name: Generate Package and Deployment Plan
        shell: |
          #!/bin/bash
          cd /runner/project
          plum-generate\
            --deploymentMethod ./plum-samples/external-repos/deployment-method/deployment-method.yml\
            --currentDeploymentState /plum-samples/external-repos/deployment-state/deployment-state.yml\
            --manifests ./plum-samples/application-manifest/application-manifest.yml\
            --deploymentPlan ./deployment-plan.yml\
            --deploymentPlanReport ./deployment-plan-report.html\
            --deploymentState ./merged-deployment-state.yml\
            --packageOutputFile ./package.tar\
            --configFile ./config.yml
           
        delegate_to: localhost
        
      - import_role:
          name: ibm.ibm_zos_plum_deploy.zos_deploy
