apiVersion: deploy.ibm.com/v1
kind: Evidence
metadata:
  annotations:
    creation_timestamp: 20240103.221058.468
    engine:
      build: manual
      date: Wed Jan  3 16:54:16 CET 2024
      version: 0.11.0
    environment_name: zos_tivlp02
    deploy_timestamp: 20240103.221102.921
    inventory_hostname: zos_tivlp02
    ansible_host: 9.30.222.103
    smf_record:
      status: Ok
  description: cics-genapp
  name: cics-genapp
  version: 1.0.40
status: Ok
activities:
- name:
  - PACKAGE
  actions:
  - name:
    - PACKAGE
    steps:
    - name:
      - PACKAGE
      step_result:
        status: Ok
        msg: 'package.yml : Ok'
        results:
        - status: Ok
          msg: 'package.yml line 14 : ibm.ibm_zos_wazi_deploy.zos_deploy : set_fact'
          results:
            register: None
            args:
              wd_package_is_remote: true
            result:
              ansible_facts:
                wd_package_is_remote: true
        - status: Skipped
          msg: 'package.yml line 17 : ibm.ibm_zos_wazi_deploy.zos_deploy : [{{current_step_name}}]:
            Set the package location'
          results:
            register: None
            args:
              wd_package_file: '{{ wd_deployment_plan.metadata.annotations.package.path
                if wd_deployment_plan.metadata.annotations.package is defined else
                None }}'
            result:
              false_condition: wd_package_file is not defined
              skip_reason: Conditional result was False
        - status: Ok
          msg: 'package.yml line 22 : ibm.ibm_zos_wazi_deploy.zos_deploy : [package>package>package]:
            Check if /var/lib/jenkins/workspace/GENAPP_WD_DYNAMIC_BETA_CD_ANSIBLE_PROJECT/BUILD-43/package.tar
            exists'
          results:
            register: wd_payload_st
            args:
              checksum_algorithm: sha256
              path: /var/lib/jenkins/workspace/GENAPP_WD_DYNAMIC_BETA_CD_ANSIBLE_PROJECT/BUILD-43/package.tar
            result:
              invocation:
                module_args:
                  checksum_algorithm: sha256
                  follow: false
                  get_attributes: true
                  get_checksum: true
                  get_md5: false
                  get_mime: true
                  path: /var/lib/jenkins/workspace/GENAPP_WD_DYNAMIC_BETA_CD_ANSIBLE_PROJECT/BUILD-43/package.tar
              stat:
                exists: false
        - status: Skipped
          msg: 'package.yml line 29 : ibm.ibm_zos_wazi_deploy.zos_deploy : [{{current_step_name}}]:
            Verify the deployment plan package section {{ wd_package_file }}'
          results:
            register: None
            args:
              msg: The deployment plan package section is not resent in the deployment
                plan!!
            result:
              false_condition: wd_payload_st.stat.exists
              skip_reason: Conditional result was False
        - status: Skipped
          msg: 'package.yml line 36 : ibm.ibm_zos_wazi_deploy.zos_deploy : [{{current_step_name}}]:
            Verify the checksum of the package {{ wd_package_file }}'
          results:
            register: None
            args:
              msg: The current package checksum {{ wd_payload_st.stat.checksum }}
                differ from the checksum in the deployment plan {{ wd_deployment_plan.metadata.annotations.package.sha256
                }}
            result:
              false_condition: wd_payload_st.stat.exists
              skip_reason: Conditional result was False
        - status: Skipped
          msg: 'package.yml line 43 : ibm.ibm_zos_wazi_deploy.zos_deploy : [{{current_step_name}}]:
            Send {{ wd_package_file }} to USS: {{ wd_env.uss_dir }}'
          results:
            register: None
            args:
              dest: '{{ wd_deploy_dir_uss }}'
              src: '{{ wd_package_file }}'
            result:
              false_condition: wd_payload_st.stat.exists and wd_package_is_remote
                | bool == True
              skip_reason: Conditional result was False
        - status: Skipped
          msg: 'package.yml line 49 : ibm.ibm_zos_wazi_deploy.zos_deploy : [{{current_step_name}}]:
            Extract {{ wd_package_file }} on USS'
          results:
            register: None
            args:
              _raw_params: |-
                set +e
                tar -C {{ wd_deploy_dir_uss }} -xf {{ wd_deploy_dir_uss }}/*.tar -L T 2>{{ wd_deploy_dir_uss }}/{{inventory_hostname}}.tar.log
                if [ $(grep -v "cannot set uid.gid" {{ wd_deploy_dir_uss }}/{{inventory_hostname}}.tar.log | wc -w) -eq 0 ]
                then
                   #chtag -r $(find {{ wd_deploy_dir_uss }} -type f)
                   exit 0
                else
                   cat {{ wd_deploy_dir_uss }}/{{inventory_hostname}}.tar.log | iconv -f ibm-1047 -t utf-8
                   exit -1
                fi
            result:
              false_condition: wd_payload_st.stat.exists and wd_package_is_remote
                | bool  == True
              skip_reason: Conditional result was False
        - status: Skipped
          msg: 'package.yml line 63 : ibm.ibm_zos_wazi_deploy.zos_deploy : [{{current_step_name}}]:
            Extract {{ wd_package_file }} locally to {{wd_deploy_dir_local}}'
          results:
            register: None
            args:
              _raw_params: tar -C {{ wd_deploy_dir_local }} -xf {{ wd_package_file
                }}
            result:
              false_condition: wd_payload_st.stat.exists and wd_package_is_remote
                | bool  == False
              skip_reason: Conditional result was False
manifests:
- annotations:
    creation_timestamp: 20240103.211401.533
    dbb:
      build_result_uri: https://zdevops-demo1.fyre.ibm.com:9443/dbb/rest/buildResult/61543
    package:
      name: sys-wazi-deploy-team/cics-genapp-wazideploy-dynamic-build
      properties:
      - key: repository_path
        value: wazideploy/dynamic/cics-genapp
      - key: repository
        value: sys-wazi-deploy-team-pentest-generic-local
      - key: build_name
        value: sys-wazi-deploy-team/cics-genapp-wazideploy-dynamic-build
      - key: build_number
        value: '28'
      type: ARTIFACTORY
      uri: https://na.artifactory.swg-devops.com/ui/builds/sys-wazi-deploy-team%2Fcics-genapp-wazideploy-dynamic-build/28
    scm:
      branch: wazideploy
      short_commit: 87b0a0f9
      type: git
      uri: git@github.com:jbyibm/cics-genapp.git
  description: cics-genapp
  name: cics-genapp
  version: 1.0.40
