apiVersion: deploy.ibm.com/v1
kind: ManifestState
metadata:
  name: cics-genapp
  description: cics-genapp
  version: 1.0.24
  annotations:
    creation_timestamp: 20240416.090242.863
    scm:
      type: git
      uri: git@github.com:jbyibm/cics-genapp.git
      branch: DIT
      short_commit: f0993a59
    package:
      name: sys-wazi-deploy-team/cics-genapp-wazideploy-static-build
      properties:
      - key: repository_path
        value: wazideploy/static/cics-genapp
      - key: repository
        value: sys-wazi-deploy-team-pentest-generic-local
      - key: build_name
        value: sys-wazi-deploy-team/cics-genapp-wazideploy-static-build
      - key: build_number
        value: '244'
      uri: https://na.artifactory.swg-devops.com/ui/builds/sys-wazi-deploy-team%2Fcics-genapp-wazideploy-static-build/244
      type: ARTIFACTORY
      is_archive: true
artifacts:
- name: LGACDB02
  description: LGACDB02.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB02.DBRM
  - key: fingerprint
    value: 97807e528973a868dd64897a187b69969be2feea51bd7265e6c813fe4a0da1e4
  type: DBRM
  hash: 0b1369b761b19bb5b7879df94457b575b021f183576458886dc11178c76dce69
- name: LGDPVS01
  description: LGDPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043531
  type: CICSLOAD
  hash: 0b73de66f9607ebd5de5e07976b60873132590df7662332e9ec2fe20d56f1768
- name: LGAPOL01
  description: LGAPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043527
  type: CICSLOAD
  hash: 164a96fea8ded0e7846648ce21d479d13bf4fc2099fe28b3fb82b680de418cf0
- name: LGICDB01
  description: LGICDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGICDB01.DBRM
  - key: fingerprint
    value: 74f3e35a8f32dd4e5b165319d482736f4c618efae1aafb5190b06bfd8fd43a50
  type: DBRM
  hash: 177d06a7d998db5cd333e46b4187dd841fd54766f745cd23e0ffc7f187374b00
- name: LGUPDB01
  description: LGUPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043543
  type: CICSLOAD
  hash: 2076fcd25a390eb3301f6a019180d98266dc3f0fd301b2817dffc8b6b1ff8309
- name: LGDPOL01
  description: LGDPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043530
  type: CICSLOAD
  hash: 23f5f97f1c9ebe6ce88b0c5214d16c1898cff87c799ad0f4ab7f17b9818df149
- name: LGACDB01
  description: LGACDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB01.DBRM
  - key: fingerprint
    value: 39aa154bdabf8ce6e6b4db11657bda632ba23081c579dade70f4a8de53da0faa
  type: DBRM
  hash: 32936aba56ea9190695c6a9e2189a549770d5a0231670ff92f0a7693f021ed3c
- name: LGDPDB01
  description: LGDPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043529
  type: CICSLOAD
  hash: 4c09b34dba3c66161a9069cf5b0f6dd0e594f2dac0d75097b1587c5263479f4e
- name: HELLO2
  description: HELLO2.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO2.JCL
  - key: fingerprint
    value: 55e756a76e9339d24e5c6c46c102faf8ea468f7f2e49867f985a47e746529c1e
  type: JCL
  hash: 55e756a76e9339d24e5c6c46c102faf8ea468f7f2e49867f985a47e746529c1e
- name: HELLO1
  description: HELLO1.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO1.JCL
  - key: fingerprint
    value: 573a056000558d6ae6887bb816a8759c57cff8f23c09261e130250307f9e767a
  type: JCL
  hash: 573a056000558d6ae6887bb816a8759c57cff8f23c09261e130250307f9e767a
- name: LGIPDB01
  description: LGIPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGIPDB01.DBRM
  - key: fingerprint
    value: a198d04942838d8be68e62e40c2a1d767be7d3b40c04b212158b5ed0ee6e1e0d
  type: DBRM
  hash: 5a5443550d80990034378c590ee2a1986f5693e0c26a1b1adeb6fef02a18ce23
- name: LGIPOL01
  description: LGIPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043536
  type: CICSLOAD
  hash: 61429f6f7c370e60c622f1e9119d66ce5bad1268a8830f54d0b69711e7458bec
- name: LGICVS01
  description: LGICVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043534
  type: CICSLOAD
  hash: 6200fd49619e1a32e9c9e7144546c55ccf86c508fddcf2c8c5bc773ed4d8f7e6
- name: LGUCVS01
  description: LGUCVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043542
  type: CICSLOAD
  hash: 631a36327b669a6b06cfe095ea8f92ec998482beb590ceb6c504776996fb3244
- name: SSMAP
  description: SSMAP.MAPLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/SSMAP.MAPLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043519
  type: MAPLOAD
  hash: 7ae23f3a6cbc51fe5958c461c20b7f6585827326300b3ced16b30d19a0959447
- name: LGIPDB01
  description: LGIPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043535
  type: CICSLOAD
  hash: 7d7c7e17b0fbb9895d94652004b82000fea91fe13f705eb65465293a78678710
- name: LGUPDB01
  description: LGUPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUPDB01.DBRM
  - key: fingerprint
    value: a71565675b337ba52308f2e4216ec7bcbad9e6f290c08652e393a28cac04ed2d
  type: DBRM
  hash: 85cc22909f39ef7c6f7cce6d1b901e34b2ceafd0d7bb71794300caebb0ea4625
- name: LGUCUS01
  description: LGUCUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043541
  type: CICSLOAD
  hash: 919029a64540449e8e92005a04b29d362d91edfa9023cdc2c27940b7e7f7ee2c
- name: LGSTSQ
  description: LGSTSQ.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSTSQ.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043539
  type: CICSLOAD
  hash: a8637bbdf19afb3e1026347e3ba3cf752f35a0656ce4eca1a524456f1be30585
- name: LGUCDB01
  description: LGUCDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043540
  type: CICSLOAD
  hash: a86782d30dbd8afc8446659d4455a3ac02ea0143c71806c9729506f7d101b4b9
- name: LGACUS01
  description: LGACUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043524
  type: CICSLOAD
  hash: b1de2617f17be1f4be6334a73a966fa0f8b71735b9268feb5ed9497677039b45
- name: LGUPVS01
  description: LGUPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043545
  type: CICSLOAD
  hash: b406a906b94e1180a9e5132b7df03a94f03b443b7861c9d696da8dba5b3d704b
- name: LGSETUP
  description: LGSETUP.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSETUP.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043538
  type: CICSLOAD
  hash: b52504c2b86e1f4b3455b2e27cbeddfa7fb251e12e5663ca4c7c1da8388c58db
- name: LGACDB02
  description: LGACDB02.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB02.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043522
  type: CICSLOAD
  hash: be30a64794ef44e55961d2bec9bdaac31225b3f72c9f2528ba313240d3ef3aaf
- name: LGIPVS01
  description: LGIPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043537
  type: CICSLOAD
  hash: c2d73a16a19a416d93bf0d4faa3818713e9e1fa436ec89aa28699c21a0756c43
- name: LGAPDB01
  description: LGAPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043526
  type: CICSLOAD
  hash: d3f164b73907c2eb17c0eb5e72820cb0ad8cb1ab55207ab1916c2c02039c4fbd
- name: LGUPOL01
  description: LGUPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043544
  type: CICSLOAD
  hash: d5c1d5e241c1f90b150ed3da8bcc2d19ae06e1312f44592dc3d3db5d6c07cc00
- name: LGAPDB01
  description: LGAPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGAPDB01.DBRM
  - key: fingerprint
    value: 35758e0798945a6a553cea809d29bf210723e924f292639262911405c4f759f6
  type: DBRM
  hash: e43163b0e0a8ae5dffe2bd4a389bc74901f572e38098a9424c4d89a4cdc96d16
- name: LGUCDB01
  description: LGUCDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUCDB01.DBRM
  - key: fingerprint
    value: 2c08c0b1942ee3eca0a2a874e5a3dd222462343377a87be6a4899e65d92d7e12
  type: DBRM
  hash: e7522984826ff5dcff499e431bd6b584c459608bbb562715535db3106e7ca2be
- name: LGICUS01
  description: LGICUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043533
  type: CICSLOAD
  hash: e78237a3926ec57a9f21d2bf4f453ff9df318fe72fa17b9639606a72af16773f
- name: LGDPDB01
  description: LGDPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGDPDB01.DBRM
  - key: fingerprint
    value: 7c021986ba7132c4e65e34ae39e442be30c260a209268ecbeb9cf1b9c2765bdc
  type: DBRM
  hash: ea4df471265baf612a4baecb7e9ec550e4bcd41a59e8c27201be931da289215c
- name: LGACDB01
  description: LGACDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043521
  type: CICSLOAD
  hash: ef2a813b24cac296d68de39cc918fabdd7f7e01b3935be7a1199e500d5d406f5
- name: LGICDB01
  description: LGICDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043532
  type: CICSLOAD
  hash: fd04b095f09aa20abcf30c1b63812c9c754b811bba614c63273a4453e1650896
- name: LGAPVS01
  description: LGAPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043528
  type: CICSLOAD
  hash: fd086fcd1155e1c9f2d643245b3a5f02f1291deeb7951c6fd0d75bff4e6d1023
- name: LGACVS01
  description: LGACVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024102043525
  type: CICSLOAD
  hash: fdf98e54aaba4573a6908ea7ff52c3fe37de3b1ace821c736c6a7227cc3f8701
