apiVersion: deploy.ibm.com/v1
kind: ManifestState
metadata:
  name: cics-genapp
  description: cics-genapp
  version: 1.0.4
  annotations:
    creation_timestamp: 20230808.145032.868
    scm:
      type: git
      uri: git@github.com:jbyibm/cics-genapp.git
      branch: wazideploy
      short_commit: 8acc4e0d
    package:
      name: sys-wazi-deploy-team/cics-genapp-wazideploy-dynamic-build
      properties:
      - key: repository_path
        value: wazideploy/dynamic/cics-genapp
      - key: repository
        value: sys-wazi-deploy-team-pentest-generic-local
      - key: build_name
        value: sys-wazi-deploy-team/cics-genapp-wazideploy-dynamic-build
      - key: build_number
        value: '1'
      uri: https://na.artifactory.swg-devops.com/ui/builds/sys-wazi-deploy-team%2Fcics-genapp-wazideploy-dynamic-build/1
      type: ARTIFACTORY
    dbb:
      build_result_uri: https://zdevops-demo1.fyre.ibm.com:9443/dbb/rest/buildResult/52437
artifacts:
- name: LGSTSQ
  description: LGSTSQ.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSTSQ.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104844
  type: CICSLOAD
  hash: 0309bb2d49ce74630a6280c01180d1485c9dbbec651622795b1f9d40b78bca9a
- name: LGAPDB01
  description: LGAPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGAPDB01.DBRM
  - key: fingerprint
    value: 03fa4650ebae3e1a3aee8db8913fd94fa8e37d82a2e7b458a84dbeb9d11736d3
  type: DBRM
  hash: 03fa4650ebae3e1a3aee8db8913fd94fa8e37d82a2e7b458a84dbeb9d11736d3
- name: LGUPDB01
  description: LGUPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUPDB01.DBRM
  - key: fingerprint
    value: 07068b6e673f90460bc84816fa41f773abdc71d083338c9cf9d22b60a936051f
  type: DBRM
  hash: 07068b6e673f90460bc84816fa41f773abdc71d083338c9cf9d22b60a936051f
- name: LGICDB01
  description: LGICDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGICDB01.DBRM
  - key: fingerprint
    value: 0a33552d5e2ad6e3a02c69af2a19b36b3c809aed3de331cfb6a4ad3dc6ba98bc
  type: DBRM
  hash: 0a33552d5e2ad6e3a02c69af2a19b36b3c809aed3de331cfb6a4ad3dc6ba98bc
- name: LGIPDB01
  description: LGIPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGIPDB01.DBRM
  - key: fingerprint
    value: 0e41a27512bbd70adcd5341165cea6bff9515fbe96fd42842c7aa7ac352b5365
  type: DBRM
  hash: 0e41a27512bbd70adcd5341165cea6bff9515fbe96fd42842c7aa7ac352b5365
- name: SSMAP
  description: SSMAP.MAPLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/SSMAP.MAPLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104836
  type: MAPLOAD
  hash: 147ad911efc3e97f324a76c73ebb5861b59a140406c015dd554b56bda7b639c5
- name: LGIPVS01
  description: LGIPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104901
  type: CICSLOAD
  hash: 1f62d14fd7a70dc82148d41835d0e9503d46689de2ef9005ae27cb138f13dd83
- name: LGAPDB01
  description: LGAPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104843
  type: CICSLOAD
  hash: 25a0d017d0fc1d385290f0e594488df5f301f62fc9361fb9ad8e7a03f8426ac3
- name: HELLO2
  description: HELLO2.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO2.JCL
  - key: fingerprint
    value: 2a305ee5391a1f7f687177e712e9eb8d3747ff1992630b36438e3bbefc162488
  type: JCL
  hash: 2a305ee5391a1f7f687177e712e9eb8d3747ff1992630b36438e3bbefc162488
- name: LGAPOL01
  description: LGAPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104849
  type: CICSLOAD
  hash: 2aaf385ad7a4bac90f0b87dd85e911ecdb92847e9d0d8df3c755c03f6275813e
- name: LGUPVS01
  description: LGUPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104849
  type: CICSLOAD
  hash: 3113cae4a5427b3f56b561cc9ef315fa97e621f42923cb2691f7c65ff9e8bdfd
- name: LGUCDB01
  description: LGUCDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104852
  type: CICSLOAD
  hash: 31bb065598ca9463806f021e6735edd814c33b0bebf1689dfd871bf780fce511
- name: LGICUS01
  description: LGICUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104839
  type: CICSLOAD
  hash: 4320aa4314e2554a737804420e3ef9538268335daeff1e3d99ceb3ce20d067ba
- name: LGACDB02
  description: LGACDB02.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB02.DBRM
  - key: fingerprint
    value: 52fd2a55b4c02ba8aa164cc197a904129ce4770be1a432d43f3e17c4e0bf42d0
  type: DBRM
  hash: 52fd2a55b4c02ba8aa164cc197a904129ce4770be1a432d43f3e17c4e0bf42d0
- name: LGDPDB01
  description: LGDPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGDPDB01.DBRM
  - key: fingerprint
    value: 573f822d3c132be94243bd33752919bf0afc0378cfba2c4367f12212e41fd2f4
  type: DBRM
  hash: 573f822d3c132be94243bd33752919bf0afc0378cfba2c4367f12212e41fd2f4
- name: LGDPVS01
  description: LGDPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104854
  type: CICSLOAD
  hash: 5bb98b8ca8cce700bb5f63e809267630b4ccacbaebf216648e09964bba636a1a
- name: LGIPDB01
  description: LGIPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104848
  type: CICSLOAD
  hash: 617545a289d9435287e5aeb8d62b2f160fd021b85f57427b5532e1d5f007ab4a
- name: LGUCDB01
  description: LGUCDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUCDB01.DBRM
  - key: fingerprint
    value: 6b3074c5b2ccce0746bd83aa3e8c263c893f185ff629b43a6e2d86f35ed06fd8
  type: DBRM
  hash: 6b3074c5b2ccce0746bd83aa3e8c263c893f185ff629b43a6e2d86f35ed06fd8
- name: HELLO1
  description: HELLO1.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO1.JCL
  - key: fingerprint
    value: 7178851f630501f1dde713b408e2d8ed2b4147638e5b818e8200851ed1a203b9
  type: JCL
  hash: 7178851f630501f1dde713b408e2d8ed2b4147638e5b818e8200851ed1a203b9
- name: LGACVS01
  description: LGACVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104846
  type: CICSLOAD
  hash: 778274cf7e344729c495134a914b6e8fa9816a59a4f068614f22a941e4d99294
- name: LGSETUP
  description: LGSETUP.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSETUP.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104856
  type: CICSLOAD
  hash: 88d46983baaa6ece972a14ac682c699e965e20547a8f080c5bb133002392ccdd
- name: LGICDB01
  description: LGICDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104857
  type: CICSLOAD
  hash: 8b9aac6a837d3065406a12f8cf3cafcaae288997cbfa42303b9b1a63ba9b57df
- name: LGDPOL01
  description: LGDPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104841
  type: CICSLOAD
  hash: 94626c2a0ff3f3214e2b8b6463815860d5837ffd648b8c4ee1c8c8a032e08799
- name: LGUPDB01
  description: LGUPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104859
  type: CICSLOAD
  hash: 98d8e59f241b0e3c15cad7435db177adfde43af79b71f0ca593ff8ba24d12d98
- name: LGUPOL01
  description: LGUPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104855
  type: CICSLOAD
  hash: 9eed382fe79078fb5e7e67084f11cc8be3c6a0ca339a8bc3b2a0b43bfd322c17
- name: LGICVS01
  description: LGICVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104842
  type: CICSLOAD
  hash: a4a7640551030c94aa80e5b26dad535d8a75925ef64f3c9af740e9a5c128f882
- name: LGACDB01
  description: LGACDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104900
  type: CICSLOAD
  hash: aa7b72927f134ae4dc1de29b4cf50173f583f9b2dfa50cd09e6822d34362c5e4
- name: LGUCVS01
  description: LGUCVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104839
  type: CICSLOAD
  hash: ac278e9075e4c86bda15a1091ef61f4bdcbfd4fa0eaeb86824629a84675e0c14
- name: LGUCUS01
  description: LGUCUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104838
  type: CICSLOAD
  hash: b00fe9652627690db9daae94d6b6f95c5e7ceeb3ba411a730cbea7c38b3935fa
- name: LGACDB01
  description: LGACDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB01.DBRM
  - key: fingerprint
    value: b47e299fc12e4dc968090d0c41158e516c63e1132fa43c2fdab7f618f8f635b9
  type: DBRM
  hash: b47e299fc12e4dc968090d0c41158e516c63e1132fa43c2fdab7f618f8f635b9
- name: LGDPDB01
  description: LGDPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104840
  type: CICSLOAD
  hash: b63246c76d62fc8e697cd81b0c49da7a30de07ed405a5a64abe3d1cd7d2bf0c4
- name: LGAPVS01
  description: LGAPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104858
  type: CICSLOAD
  hash: b71fe9f0ac5d3d1af6aa1d50c042b161e071bd369f24867ae2725533b7ce1e36
- name: LGIPOL01
  description: LGIPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104850
  type: CICSLOAD
  hash: c4d23fe958cb24b1830e3e4ad2d98d6929c3894c3a431de9573320d11acbf615
- name: LGACUS01
  description: LGACUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104845
  type: CICSLOAD
  hash: ec6445a394e70f9ddda085b3f9ce4dfc9c8c1ca8c4bd5cc092c7389ef1f36d35
- name: LGACDB02
  description: LGACDB02.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB02.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023220104851
  type: CICSLOAD
  hash: fe4de74cd5f5cdd099d29bf264f98f81b7d6ea60ac6cfe4e0ececcfbb394fef3
