apiVersion: deploy.ibm.com/v1
kind: ManifestState
metadata:
  name: cics-genapp
  description: cics-genapp
  version: 1.0.12
  annotations:
    creation_timestamp: 20240401.082224.101
    scm:
      type: git
      uri: git@github.com:jbyibm/cics-genapp.git
      branch: DIT
      short_commit: 75c59fe5
    package:
      name: sys-wazi-deploy-team/cics-genapp-wazideploy-static-build
      properties:
      - key: repository_path
        value: wazideploy/static/cics-genapp
      - key: repository
        value: sys-wazi-deploy-team-pentest-generic-local
      - key: build_name
        value: sys-wazi-deploy-team/cics-genapp-wazideploy-static-build
      - key: build_number
        value: '249'
      uri: https://na.artifactory.swg-devops.com/ui/builds/sys-wazi-deploy-team%2Fcics-genapp-wazideploy-static-build/249
      type: ARTIFACTORY
      is_archive: true
artifacts:
- name: LGACDB02
  description: LGACDB02.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB02.DBRM
  - key: fingerprint
    value: 67d248b4ba2a3b9bd9c71525da57e61347d58f2098dec1e39be4f9844f313920
  type: DBRM
  hash: 67d248b4ba2a3b9bd9c71525da57e61347d58f2098dec1e39be4f9844f313920
- name: LGACDB02
  description: LGACDB02.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB02.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042024092042219
  type: CICSLOAD
  hash: fdbc9c78f120fe5c6d94a43f7fedd659bb178b7be0e81a79843af0365a36db51
