---

- hosts: localhost
  gather_facts: false
  environment:
    ANSIBLE_STDOUT_CALLBACK: default
    ANSIBLE_CALLBACK_PLUGINS: ''
    ANSIBLE_NOCOLOR: True
  vars:
    msg: 'hello'

  tasks:
    - command: 'ansible-playbook debug.yml'
      register: output

    - debug:
        var: output.stdout_lines
