#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
PYZ: "/var/imsapp/python/usr/lpp/IBM/cyp/v3r12/pyz"
ZOAU: "/var/usr/lpp/IBM/zoautil/v1.2.5.4"
