---
apiVersion: deploy.ibm.com/v1
kind: DeploymentMethod
metadata:
  name: "CICS"
  version: "1.0.0"
  description: |
    This deployment method can be use for the deployment of an CICS application.
  annotations:
    deployVersion: "1.0.0"

activities:
  - name: PACKAGE
    description: |
      This activity handle the package
    actions:
        - name: PACKAGE
          steps:
          - name: PACKAGE
    plan_tags:
      - package

  - name: DEPLOY_MODULES
    description: |
      This activity is dedicated to the deployment of the artifacts into the PDS 
    actions:
        - name: UPDATE
          description: |
            This action is applicable when we udpate artifacts.
          states:
             - UNDEFINED
          steps:
          - name: MEMBER_ARCHIVE
            description: |
              This step do the copy of artifacts into PDSs
            properties:
            - key: "path_filter"
              value: ".*LGA.*"
          - name: MEMBER_RESTORE
            description: |
              This step do the copy of artifacts into PDSs
            plan_tags:
            - restore
            - never
          - name: MEMBER_COPY
            description: |
              This step do the copy of artifacts into PDSs
    types:
      - name: 'DBRM'
      #- name: 'LOAD'
      - name: 'CICSLOAD'
      - name: 'MAPLOAD'
      #- name: 'JCL'
      #- name: 'LISTING'
      #- name: 'SIDEFILE'
      #- name: 'CEXEC'
    is_artifact: True
    tags:
      - deploy_module

  - name: DB2
    description: |
      This activity is dedicated to DBRM bind modules
    actions:
        - name: UPDATE
          description: |
            This action is applicable when we update a DBRM modules
          states:
             - UNDEFINED
          steps:
          - name: DB2_BIND_PACKAGE
          - name: DB2_BIND_PLAN
    types:
      - name: 'DBRM'
    is_artifact: True
    plan_tags:
    - restore
    - db2
        
  - name: CICS
    description: |
       This activity is dedicated to CICS load modules
    actions:
        - name: UPDATE
          states:
             - UNDEFINED
          steps:
          - name: PROG_UPDATE
            properties:
            - key: "template"
              value: "cics_cmci_prog_update"
    types:
      - name: 'CICSLOAD'
      - name: 'MAPLOAD'
    is_artifact: True
    plan_tags:
    - restore
    - db2

  - name: DELETE_MODULES
    description: |
      This activity is dedicated to the deletion of the artifacts from the PDS(E)s 
    actions:
        - name: DELETE
          description: |
            This action is applicable when the artifacts are deleted
          states:
             - DELETED
          steps:
          - name: MEMBER_ARCHIVE
            description: |
              This step backs up already installed artifacts into the backup PDS
          - name: MEMBER_DELETE
            description: |
              This step deletes the artifacts 
    types:
      - name: 'DBRM'
      - name: 'LOAD'
      - name: 'CICSLOAD'
      - name: 'MAPLOAD'
      - name: 'JCL'
    is_artifact: True