-- *******************************************************************************
-- Licensed Materials - Property of IBM
-- (c) Copyright IBM Corp. 2025. All Rights Reserved.
--
-- Note to U.S. Government Users Restricted Rights:
-- Use, duplication or disclosure restricted by GSA ADP Schedule
-- Contract with IBM Corp.
-- *******************************************************************************

-- DB2 Evidence Loader - Database Schema
-- This script creates the database structure for storing deployment evidence

-- =============================================================================
-- 1. DEPLOY TABLE (Main deployment information)
-- =============================================================================

CREATE TABLE DEPLOYZ.DEPLOY (
    DEPLOY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DESCRIPTION VARCHAR(1000),
    APPLICATION_NAME VARCHAR(255),
    APPLICATION_VERSION VARCHAR(50),
    ENVIRONMENT_NAME VARCHAR(255),
    DEPLOY_TIMESTAMP TIMESTAMP,
    CREATION_TIMESTAMP TIMESTAMP,
    STATUS VARCHAR(50),
    ENGINE_VERSION VARCHAR(50),
    ENGINE_BUILD VARCHAR(50),
    ENGINE_DATE TIMESTAMP,
    PACKAGE_PATH VARCHAR(500),
    PACKAGE_SHA256 VARCHAR(64),
    PRIMARY KEY (DEPLOY_ID)
);

-- =============================================================================
-- 2. ACTIVITY TABLE
-- =============================================================================

CREATE TABLE DEPLOYZ.ACTIVITY (
    ACTIVITY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DEPLOY_ID INTEGER NOT NULL,
    ACTIVITY_NAME VARCHAR(255),
    SHORT_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(1000),
    STATUS VARCHAR(50),
    MESSAGE VARCHAR(2000),
    PRIMARY KEY (ACTIVITY_ID),
    FOREIGN KEY (DEPLOY_ID) REFERENCES DEPLOYZ.DEPLOY(DEPLOY_ID) ON DELETE CASCADE
);

CREATE INDEX DEPLOYZ.IDX_ACTIVITY_DEPLOY ON DEPLOYZ.ACTIVITY(DEPLOY_ID);

-- =============================================================================
-- 3. ACTION TABLE
-- =============================================================================

CREATE TABLE DEPLOYZ.ACTION (
    ACTION_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ACTIVITY_ID INTEGER NOT NULL,
    ACTION_NAME VARCHAR(255),
    SHORT_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(1000),
    STATUS VARCHAR(50),
    MESSAGE VARCHAR(2000),
    PRIMARY KEY (ACTION_ID),
    FOREIGN KEY (ACTIVITY_ID) REFERENCES DEPLOYZ.ACTIVITY(ACTIVITY_ID) ON DELETE CASCADE
);

CREATE INDEX DEPLOYZ.IDX_ACTION_ACTIVITY ON DEPLOYZ.ACTION(ACTIVITY_ID);

-- =============================================================================
-- 4. STEP TABLE
-- =============================================================================

CREATE TABLE DEPLOYZ.STEP (
    STEP_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ACTION_ID INTEGER NOT NULL,
    STEP_NAME VARCHAR(255),
    SHORT_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(1000),
    STATUS VARCHAR(50),
    MESSAGE VARCHAR(2000),
    BUILDING_BLOCK VARCHAR(100) DEFAULT '',
    PRIMARY KEY (STEP_ID),
    FOREIGN KEY (ACTION_ID) REFERENCES DEPLOYZ.ACTION(ACTION_ID) ON DELETE CASCADE
);

CREATE INDEX DEPLOYZ.IDX_STEP_ACTION ON DEPLOYZ.STEP(ACTION_ID);

-- =============================================================================
-- 5. TAG TABLE (Unique tags)
-- =============================================================================

CREATE TABLE DEPLOYZ.TAG (
    TAG_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TAG_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (TAG_ID),
    CONSTRAINT UQ_TAG_NAME UNIQUE (TAG_NAME)
);

-- =============================================================================
-- 6. ACTIVITY_TAG TABLE (Many-to-Many relationship)
-- =============================================================================

CREATE TABLE DEPLOYZ.ACTIVITY_TAG (
    ACTIVITY_ID INTEGER NOT NULL,
    TAG_ID INTEGER NOT NULL,
    PRIMARY KEY (ACTIVITY_ID, TAG_ID),
    FOREIGN KEY (ACTIVITY_ID) REFERENCES DEPLOYZ.ACTIVITY(ACTIVITY_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES DEPLOYZ.TAG(TAG_ID) ON DELETE CASCADE
);

CREATE INDEX DEPLOYZ.IDX_ACTIVITY_TAG_ACTIVITY ON DEPLOYZ.ACTIVITY_TAG(ACTIVITY_ID);
CREATE INDEX DEPLOYZ.IDX_ACTIVITY_TAG_TAG ON DEPLOYZ.ACTIVITY_TAG(TAG_ID);

-- =============================================================================
-- 7. ACTION_TAG TABLE (Many-to-Many relationship)
-- =============================================================================

CREATE TABLE DEPLOYZ.ACTION_TAG (
    ACTION_ID INTEGER NOT NULL,
    TAG_ID INTEGER NOT NULL,
    PRIMARY KEY (ACTION_ID, TAG_ID),
    FOREIGN KEY (ACTION_ID) REFERENCES DEPLOYZ.ACTION(ACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES DEPLOYZ.TAG(TAG_ID) ON DELETE CASCADE
);

CREATE INDEX DEPLOYZ.IDX_ACTION_TAG_ACTION ON DEPLOYZ.ACTION_TAG(ACTION_ID);
CREATE INDEX DEPLOYZ.IDX_ACTION_TAG_TAG ON DEPLOYZ.ACTION_TAG(TAG_ID);

-- =============================================================================
-- 8. STEP_TAG TABLE (Many-to-Many relationship)
-- =============================================================================

CREATE TABLE DEPLOYZ.STEP_TAG (
    STEP_ID INTEGER NOT NULL,
    TAG_ID INTEGER NOT NULL,
    PRIMARY KEY (STEP_ID, TAG_ID),
    FOREIGN KEY (STEP_ID) REFERENCES DEPLOYZ.STEP(STEP_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES DEPLOYZ.TAG(TAG_ID) ON DELETE CASCADE
);

CREATE INDEX DEPLOYZ.IDX_STEP_TAG_STEP ON DEPLOYZ.STEP_TAG(STEP_ID);
CREATE INDEX DEPLOYZ.IDX_STEP_TAG_TAG ON DEPLOYZ.STEP_TAG(TAG_ID);

-- =============================================================================
-- 9. ARTIFACT TABLE (Unique artifacts by APPLICATION_NAME + PATH)
-- =============================================================================

CREATE TABLE DEPLOYZ.ARTIFACT (
    ARTIFACT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    APPLICATION_NAME VARCHAR(255) NOT NULL,
    ARTIFACT_NAME VARCHAR(255),
    ARTIFACT_PATH VARCHAR(1000) NOT NULL,
    ARTIFACT_TYPE VARCHAR(100),
    PRIMARY KEY (ARTIFACT_ID),
    CONSTRAINT UQ_ARTIFACT_APP_PATH UNIQUE (APPLICATION_NAME, ARTIFACT_PATH)
);

-- =============================================================================
-- 10. STEP_ARTIFACT TABLE (Many-to-Many relationship)
-- =============================================================================

CREATE TABLE DEPLOYZ.STEP_ARTIFACT (
    STEP_ID INTEGER NOT NULL,
    ARTIFACT_ID INTEGER NOT NULL,
    PRIMARY KEY (STEP_ID, ARTIFACT_ID),
    FOREIGN KEY (STEP_ID) REFERENCES DEPLOYZ.STEP(STEP_ID) ON DELETE CASCADE,
    FOREIGN KEY (ARTIFACT_ID) REFERENCES DEPLOYZ.ARTIFACT(ARTIFACT_ID) ON DELETE CASCADE
);

CREATE INDEX DEPLOYZ.IDX_STEP_ARTIFACT_STEP ON DEPLOYZ.STEP_ARTIFACT(STEP_ID);
CREATE INDEX DEPLOYZ.IDX_STEP_ARTIFACT_ARTIFACT ON DEPLOYZ.STEP_ARTIFACT(ARTIFACT_ID);

-- =============================================================================
-- 11. PROPERTIES TABLE (Generic key-value properties)
-- =============================================================================

CREATE TABLE DEPLOYZ.PROPERTIES (
    PROPERTY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    ENTITY_ID INTEGER NOT NULL,
    PROPERTY_KEY VARCHAR(255) NOT NULL,
    PROPERTY_VALUE VARCHAR(4000),
    DEPLOY_ID INTEGER,
    PRIMARY KEY (PROPERTY_ID)
);

CREATE INDEX DEPLOYZ.IDX_PROPERTIES_ENTITY ON DEPLOYZ.PROPERTIES(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX DEPLOYZ.IDX_PROPERTIES_KEY ON DEPLOYZ.PROPERTIES(PROPERTY_KEY);

ALTER TABLE DEPLOYZ.PROPERTIES
ADD CONSTRAINT CK_PROPERTIES_ENTITY_TYPE 
CHECK (ENTITY_TYPE IN ('ACTIVITY', 'ACTION', 'STEP', 'ARTIFACT'));

ALTER TABLE DEPLOYZ.PROPERTIES
ADD CONSTRAINT FK_PROPERTIES_DEPLOY
FOREIGN KEY (DEPLOY_ID) REFERENCES DEPLOYZ.DEPLOY(DEPLOY_ID)
ON DELETE CASCADE;

-- =============================================================================
-- 12. STEP_RESULT_DETAIL TABLE
-- =============================================================================

CREATE TABLE DEPLOYZ.STEP_RESULT_DETAIL (
    RESULT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    STEP_ID INTEGER NOT NULL,
    STATUS VARCHAR(50),
    MESSAGE VARCHAR(2000),
    COMMAND VARCHAR(4000),
    RESULT_COMMAND VARCHAR(4000),
    PRIMARY KEY (RESULT_ID),
    FOREIGN KEY (STEP_ID) REFERENCES DEPLOYZ.STEP(STEP_ID) ON DELETE CASCADE
);

CREATE INDEX DEPLOYZ.IDX_RESULT_STEP ON DEPLOYZ.STEP_RESULT_DETAIL(STEP_ID);


-- =============================================================================
-- VIEWS FOR EASIER QUERYING
-- =============================================================================

-- View: All artifacts with their usage count per application
CREATE VIEW DEPLOYZ.V_ARTIFACT_USAGE AS
SELECT 
    a.ARTIFACT_ID,
    a.APPLICATION_NAME,
    a.ARTIFACT_NAME,
    a.ARTIFACT_PATH,
    a.ARTIFACT_TYPE,
    COUNT(DISTINCT sa.STEP_ID) AS USAGE_COUNT
FROM DEPLOYZ.ARTIFACT a
LEFT JOIN DEPLOYZ.STEP_ARTIFACT sa ON a.ARTIFACT_ID = sa.ARTIFACT_ID
GROUP BY a.ARTIFACT_ID, a.APPLICATION_NAME, a.ARTIFACT_NAME, a.ARTIFACT_PATH, a.ARTIFACT_TYPE;

-- View: Complete deployment hierarchy
CREATE VIEW DEPLOYZ.V_DEPLOYMENT_HIERARCHY AS
SELECT 
    d.DEPLOY_ID,
    d.APPLICATION_NAME,
    d.ENVIRONMENT_NAME,
    d.DEPLOY_TIMESTAMP,
    d.STATUS AS DEPLOY_STATUS,
    act.ACTIVITY_ID,
    act.ACTIVITY_NAME,
    act.STATUS AS ACTIVITY_STATUS,
    a.ACTION_ID,
    a.ACTION_NAME,
    a.STATUS AS ACTION_STATUS,
    s.STEP_ID,
    s.STEP_NAME,
    s.STATUS AS STEP_STATUS
FROM DEPLOYZ.DEPLOY d
LEFT JOIN DEPLOYZ.ACTIVITY act ON d.DEPLOY_ID = act.DEPLOY_ID
LEFT JOIN DEPLOYZ.ACTION a ON act.ACTIVITY_ID = a.ACTIVITY_ID
LEFT JOIN DEPLOYZ.STEP s ON a.ACTION_ID = s.ACTION_ID;

-- View: Steps with their artifacts
CREATE VIEW DEPLOYZ.V_STEP_ARTIFACTS AS
SELECT 
    s.STEP_ID,
    s.STEP_NAME,
    s.STATUS AS STEP_STATUS,
    art.ARTIFACT_ID,
    art.APPLICATION_NAME,
    art.ARTIFACT_NAME,
    art.ARTIFACT_PATH,
    art.ARTIFACT_TYPE
FROM DEPLOYZ.STEP s
INNER JOIN DEPLOYZ.STEP_ARTIFACT sa ON s.STEP_ID = sa.STEP_ID
INNER JOIN DEPLOYZ.ARTIFACT art ON sa.ARTIFACT_ID = art.ARTIFACT_ID;

-- View: Activities with their tags (using LISTAGG for DB2 compatibility)
CREATE VIEW DEPLOYZ.V_ACTIVITY_TAGS AS
SELECT 
    a.ACTIVITY_ID,
    a.ACTIVITY_NAME,
    a.SHORT_NAME,
    LISTAGG(t.TAG_NAME, ',') WITHIN GROUP (ORDER BY t.TAG_NAME) AS TAGS
FROM DEPLOYZ.ACTIVITY a
LEFT JOIN DEPLOYZ.ACTIVITY_TAG at ON a.ACTIVITY_ID = at.ACTIVITY_ID
LEFT JOIN DEPLOYZ.TAG t ON at.TAG_ID = t.TAG_ID
GROUP BY a.ACTIVITY_ID, a.ACTIVITY_NAME, a.SHORT_NAME;

-- View: Actions with their tags (using LISTAGG for DB2 compatibility)
CREATE VIEW DEPLOYZ.V_ACTION_TAGS AS
SELECT 
    ac.ACTION_ID,
    ac.ACTION_NAME,
    ac.SHORT_NAME,
    LISTAGG(ac_t.TAG_NAME, ',') WITHIN GROUP (ORDER BY ac_t.TAG_NAME) AS TAGS
FROM DEPLOYZ.ACTION ac
LEFT JOIN DEPLOYZ.ACTION_TAG act ON ac.ACTION_ID = act.ACTION_ID
LEFT JOIN DEPLOYZ.TAG ac_t ON act.TAG_ID = ac_t.TAG_ID
GROUP BY ac.ACTION_ID, ac.ACTION_NAME, ac.SHORT_NAME;

-- View: Steps with their tags (using LISTAGG for DB2 compatibility)
CREATE VIEW DEPLOYZ.V_STEP_TAGS AS
SELECT 
    s.STEP_ID,
    s.STEP_NAME,
    s.SHORT_NAME,
    LISTAGG(s_t.TAG_NAME, ',') WITHIN GROUP (ORDER BY s_t.TAG_NAME) AS TAGS
FROM DEPLOYZ.STEP s
LEFT JOIN DEPLOYZ.STEP_TAG st ON s.STEP_ID = st.STEP_ID
LEFT JOIN DEPLOYZ.TAG s_t ON st.TAG_ID = s_t.TAG_ID
GROUP BY s.STEP_ID, s.STEP_NAME, s.SHORT_NAME;

-- =============================================================================
-- GRANTS (adjust as needed for your security model)
-- =============================================================================

-- =============================================================================
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.DEPLOY TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.ACTIVITY TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.ACTION TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.STEP TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.TAG TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.ACTIVITY_TAG TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.ACTION_TAG TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.STEP_TAG TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.ARTIFACT TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.STEP_ARTIFACT TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.PROPERTIES TO USER deployer;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DEPLOYZ.STEP_RESULT_DETAIL TO USER deployer;
-- =============================================================================

-- =============================================================================
-- END OF SCHEMA
-- =============================================================================