-- Get overall artifacts status in PROD
WITH ARTIFACT_TIMELINE AS (
    SELECT
        art.ARTIFACT_ID,
        art.ARTIFACT_NAME,
        art.ARTIFACT_PATH,
        art.ARTIFACT_TYPE,
        d.APPLICATION_NAME,
        d.DEPLOY_ID,
        d.DEPLOY_TIMESTAMP,
        s.STEP_NAME,
        s.BUILDING_BLOCK,
        CASE
            WHEN s.BUILDING_BLOCK = 'MEMBER_DELETE' THEN 'DELETED'
            ELSE 'DEPLOYED'
        END AS ACTION_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY art.ARTIFACT_ID
            ORDER BY d.DEPLOY_TIMESTAMP DESC
        ) AS RECENCY_RANK
    FROM DEPLOYZ.DEPLOY d
    INNER JOIN DEPLOYZ.ACTIVITY act ON d.DEPLOY_ID = act.DEPLOY_ID
    INNER JOIN DEPLOYZ.ACTION a ON act.ACTIVITY_ID = a.ACTIVITY_ID
    INNER JOIN DEPLOYZ.STEP s ON a.ACTION_ID = s.ACTION_ID
    INNER JOIN DEPLOYZ.STEP_ARTIFACT sa ON s.STEP_ID = sa.STEP_ID
    INNER JOIN DEPLOYZ.ARTIFACT art ON sa.ARTIFACT_ID = art.ARTIFACT_ID
    WHERE d.ENVIRONMENT_NAME = 'PROD'
),
ARTIFACT_STATUS AS (
    SELECT
        APPLICATION_NAME,
        ARTIFACT_ID,
        ARTIFACT_NAME,
        ARTIFACT_PATH,
        ARTIFACT_TYPE,
        DEPLOY_TIMESTAMP AS LAST_ACTION_DATE,
        BUILDING_BLOCK AS LAST_BUILDING_BLOCK,
        MAX(CASE WHEN ACTION_TYPE = 'DELETED' THEN 1 ELSE 0 END)
            OVER (PARTITION BY ARTIFACT_ID) AS HAS_MEMBER_DELETE,
        MAX(CASE WHEN BUILDING_BLOCK = 'MEMBER_COPY' AND ACTION_TYPE = 'DEPLOYED' THEN 1 ELSE 0 END)
            OVER (PARTITION BY ARTIFACT_ID) AS HAS_MEMBER_COPY_AFTER_DELETE
    FROM ARTIFACT_TIMELINE
    WHERE RECENCY_RANK = 1
)
SELECT
    APPLICATION_NAME,
    ARTIFACT_ID,
    ARTIFACT_NAME,
    ARTIFACT_PATH,
    ARTIFACT_TYPE,
    CASE
        WHEN HAS_MEMBER_DELETE = 1 AND HAS_MEMBER_COPY_AFTER_DELETE = 0
            THEN 'DELETED'
        ELSE 'DEPLOYED'
    END AS STATUS,
    LAST_ACTION_DATE,
    LAST_BUILDING_BLOCK
FROM ARTIFACT_STATUS
ORDER BY
    LAST_ACTION_DATE DESC,
    APPLICATION_NAME,
    ARTIFACT_NAME;
