-- Get all failed steps with context
SELECT 
    d.DEPLOY_ID,
    d.EVIDENCE_NAME,
    d.ENVIRONMENT_NAME,
    act.ACTIVITY_NAME,
    a.ACTION_NAME,
    s.STEP_ID,
    s.STEP_NAME,
    s.STATUS,
    s.MESSAGE,
    s.DURATION
FROM DEPLOYZ.STEP s
INNER JOIN DEPLOYZ.ACTION a ON s.ACTION_ID = a.ACTION_ID
INNER JOIN DEPLOYZ.ACTIVITY act ON a.ACTIVITY_ID = act.ACTIVITY_ID
INNER JOIN DEPLOYZ.DEPLOY d ON act.DEPLOY_ID = d.DEPLOY_ID
WHERE s.STATUS = 'FAILED'
ORDER BY d.DEPLOY_TIMESTAMP DESC, s.STEP_ID;
