-- Get all deployments with basic info
SELECT 
    DEPLOY_ID,
    EVIDENCE_NAME,
    DESCRIPTION,
    ENVIRONMENT_NAME,
    DEPLOY_TIMESTAMP,
    STATUS,
    ENGINE_VERSION
FROM DEPLOYZ.DEPLOY
ORDER BY DEPLOY_TIMESTAMP DESC
FETCH FIRST 20 ROWS ONLY;
