-- Get artifacts used by multiple steps
SELECT 
    a.ARTIFACT_ID,
    a.ARTIFACT_NAME,
    a.ARTIFACT_PATH,
    a.ARTIFACT_TYPE,
    COUNT(DISTINCT sa.STEP_ID) AS USAGE_COUNT,
    COUNT(DISTINCT d.DEPLOY_ID) AS DEPLOYMENT_COUNT
FROM DEPLOYZ.ARTIFACT a
INNER JOIN DEPLOYZ.STEP_ARTIFACT sa ON a.ARTIFACT_ID = sa.ARTIFACT_ID
INNER JOIN DEPLOYZ.STEP s ON sa.STEP_ID = s.STEP_ID
INNER JOIN DEPLOYZ.ACTION act ON s.ACTION_ID = act.ACTION_ID
INNER JOIN DEPLOYZ.ACTIVITY actv ON act.ACTIVITY_ID = actv.ACTIVITY_ID
INNER JOIN DEPLOYZ.DEPLOY d ON actv.DEPLOY_ID = d.DEPLOY_ID
GROUP BY a.ARTIFACT_ID, a.ARTIFACT_NAME, a.ARTIFACT_PATH, a.ARTIFACT_TYPE
HAVING COUNT(DISTINCT sa.STEP_ID) > 1
ORDER BY USAGE_COUNT DESC;
