-- =====================================================
-- DB2 Schema for Wazi Deploy Evidences
-- =====================================================

-- Main SCHEMA DEPLOYZ
CREATE SCHEMA DEPLOYZ;
SET CURRENT SCHEMA DEPLOYZ;

-- Main DEPLOY table
CREATE TABLE DEPLOY (
    DEPLOY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    EVIDENCE_NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(256),
    ENVIRONMENT_NAME VARCHAR(128),
    DEPLOY_TIMESTAMP TIMESTAMP NOT NULL,
    CREATION_TIMESTAMP TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL,
    ENGINE_VERSION VARCHAR(20),
    ENGINE_BUILD VARCHAR(50),
    ENGINE_DATE TIMESTAMP,
    PACKAGE_PATH VARCHAR(512),
    PACKAGE_SHA256 VARCHAR(64),
    ZOAU_VERSION VARCHAR(20),
    SMF_RECORD_STATUS VARCHAR(20),
    PRIMARY KEY (DEPLOY_ID)
);

CREATE INDEX IDX_DEPLOY_STATUS ON DEPLOY(STATUS);
CREATE INDEX IDX_DEPLOY_TIMESTAMP ON DEPLOY(DEPLOY_TIMESTAMP);
CREATE INDEX IDX_DEPLOY_ENV ON DEPLOY(ENVIRONMENT_NAME);

-- ACTIVITY table
CREATE TABLE ACTIVITY (
    ACTIVITY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    DEPLOY_ID INTEGER NOT NULL,
    ACTIVITY_NAME VARCHAR(128) NOT NULL,
    SHORT_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(512),
    STATUS VARCHAR(20) NOT NULL,
    MESSAGE VARCHAR(512),
    LOOP_INDEX INTEGER,
    PRIMARY KEY (ACTIVITY_ID),
    FOREIGN KEY (DEPLOY_ID) REFERENCES DEPLOY(DEPLOY_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ACTIVITY_DEPLOY ON ACTIVITY(DEPLOY_ID);
CREATE INDEX IDX_ACTIVITY_STATUS ON ACTIVITY(STATUS);

-- ACTION table
CREATE TABLE ACTION (
    ACTION_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ACTIVITY_ID INTEGER NOT NULL,
    ACTION_NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(512),
    STATUS VARCHAR(20) NOT NULL,
    MESSAGE VARCHAR(512),
    LOOP_INDEX INTEGER,
    PRIMARY KEY (ACTION_ID),
    FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY(ACTIVITY_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ACTION_ACTIVITY ON ACTION(ACTIVITY_ID);
CREATE INDEX IDX_ACTION_STATUS ON ACTION(STATUS);

-- STEP table
CREATE TABLE STEP (
    STEP_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ACTION_ID INTEGER NOT NULL,
    STEP_NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(512),
    STATUS VARCHAR(20) NOT NULL,
    MESSAGE VARCHAR(512),
    DURATION DECIMAL(15,6),
    LOOP_INDEX INTEGER,
    PRIMARY KEY (STEP_ID),
    FOREIGN KEY (ACTION_ID) REFERENCES ACTION(ACTION_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_STEP_ACTION ON STEP(ACTION_ID);
CREATE INDEX IDX_STEP_STATUS ON STEP(STATUS);

-- Generic PROPERTIES table for ACTIVITY, ACTION, and STEP
CREATE TABLE PROPERTIES (
    PROPERTY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ENTITY_TYPE VARCHAR(20) NOT NULL,  -- 'ACTIVITY', 'ACTION', or 'STEP'
    ENTITY_ID INTEGER NOT NULL,        -- Reference to ACTIVITY_ID, ACTION_ID, or STEP_ID
    PROPERTY_KEY VARCHAR(128) NOT NULL,
    PROPERTY_VALUE VARCHAR(512),
    PRIMARY KEY (PROPERTY_ID)
);

CREATE INDEX IDX_PROPERTIES_ENTITY ON PROPERTIES(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_PROPERTIES_KEY ON PROPERTIES(PROPERTY_KEY);

-- ARTIFACT table
CREATE TABLE ARTIFACT (
    ARTIFACT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    STEP_ID INTEGER NOT NULL,
    ARTIFACT_NAME VARCHAR(128) NOT NULL,
    ARTIFACT_HASH VARCHAR(64),
    ARTIFACT_PATH VARCHAR(512),
    ARTIFACT_TYPE VARCHAR(50),
    WD_MANIFEST_INDEX INTEGER,
    PRIMARY KEY (ARTIFACT_ID),
    FOREIGN KEY (STEP_ID) REFERENCES STEP(STEP_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ARTIFACT_STEP ON ARTIFACT(STEP_ID);
CREATE INDEX IDX_ARTIFACT_HASH ON ARTIFACT(ARTIFACT_HASH);
CREATE INDEX IDX_ARTIFACT_TYPE ON ARTIFACT(ARTIFACT_TYPE);

-- STEP_RESULT_DETAIL table
CREATE TABLE STEP_RESULT_DETAIL (
    RESULT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    STEP_ID INTEGER NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    MESSAGE CLOB(10K),
    COMMAND CLOB(10K),
    RESULT_COMMAND CLOB(10K),
    RETURN_CODE INTEGER,
    PRIMARY KEY (RESULT_ID),
    FOREIGN KEY (STEP_ID) REFERENCES STEP(STEP_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_RESULT_STEP ON STEP_RESULT_DETAIL(STEP_ID);

-- =====================================================
-- Useful views for common queries
-- =====================================================
-- Deployment summary view
CREATE VIEW V_DEPLOY_SUMMARY AS
SELECT 
    D.DEPLOY_ID,
    D.EVIDENCE_NAME,
    D.ENVIRONMENT_NAME,
    D.DEPLOY_TIMESTAMP,
    D.STATUS,
    COUNT(DISTINCT A.ACTIVITY_ID) AS TOTAL_ACTIVITIES,
    SUM(CASE WHEN A.STATUS = 'Ok' THEN 1 ELSE 0 END) AS SUCCESS_ACTIVITIES,
    SUM(CASE WHEN A.STATUS = 'Skipped' THEN 1 ELSE 0 END) AS SKIPPED_ACTIVITIES,
    SUM(CASE WHEN A.STATUS NOT IN ('Ok', 'Skipped') THEN 1 ELSE 0 END) AS FAILED_ACTIVITIES
FROM DEPLOY D
LEFT JOIN ACTIVITY A ON D.DEPLOY_ID = A.DEPLOY_ID
GROUP BY D.DEPLOY_ID, D.EVIDENCE_NAME, D.ENVIRONMENT_NAME, D.DEPLOY_TIMESTAMP, D.STATUS;

-- Deployed artifacts view
CREATE VIEW V_ARTIFACTS_DEPLOYED AS
SELECT 
    D.DEPLOY_ID,
    D.ENVIRONMENT_NAME,
    D.DEPLOY_TIMESTAMP,
    A.ACTIVITY_NAME,
    AC.ACTION_NAME,
    S.STEP_NAME,
    ART.ARTIFACT_NAME,
    ART.ARTIFACT_TYPE,
    ART.ARTIFACT_PATH,
    ART.ARTIFACT_HASH,
    S.STATUS AS STEP_STATUS
FROM DEPLOY D
JOIN ACTIVITY A ON D.DEPLOY_ID = A.DEPLOY_ID
JOIN ACTION AC ON A.ACTIVITY_ID = AC.ACTIVITY_ID
JOIN STEP S ON AC.ACTION_ID = S.ACTION_ID
JOIN ARTIFACT ART ON S.STEP_ID = ART.STEP_ID;

-- =====================================================
-- Table comments
-- =====================================================

COMMENT ON TABLE DEPLOY IS 'Main table containing deployment information';
COMMENT ON TABLE ACTIVITY IS 'Activities executed during deployment';
COMMENT ON TABLE ACTION IS 'Actions executed within an activity';
COMMENT ON TABLE STEP IS 'Execution steps of an action';
COMMENT ON TABLE PROPERTIES IS 'Generic properties table for ACTIVITY, ACTION, and STEP entities';
COMMENT ON TABLE ARTIFACT IS 'Deployed artifacts (JCL, LOADLIB, DBRM, etc.)';
COMMENT ON TABLE STEP_RESULT_DETAIL IS 'Detailed results of step execution';
