-- Get detailed summary for deployment ID 1
SELECT 
    d.DEPLOY_ID,
    d.APPLICATION_NAME,
    d.STATUS AS DEPLOY_STATUS,
    COUNT(DISTINCT act.ACTIVITY_ID) AS TOTAL_ACTIVITIES,
    COUNT(DISTINCT a.ACTION_ID) AS TOTAL_ACTIONS,
    COUNT(DISTINCT s.STEP_ID) AS TOTAL_STEPS,
    COUNT(DISTINCT art.ARTIFACT_ID) AS TOTAL_ARTIFACTS,
    SUM(CASE WHEN s.STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESSFUL_STEPS,
    SUM(CASE WHEN s.STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_STEPS
FROM DEPLOYZ.DEPLOY d
LEFT JOIN DEPLOYZ.ACTIVITY act ON d.DEPLOY_ID = act.DEPLOY_ID
LEFT JOIN DEPLOYZ.ACTION a ON act.ACTIVITY_ID = a.ACTIVITY_ID
LEFT JOIN DEPLOYZ.STEP s ON a.ACTION_ID = s.ACTION_ID
LEFT JOIN DEPLOYZ.STEP_ARTIFACT sa ON s.STEP_ID = sa.STEP_ID
LEFT JOIN DEPLOYZ.ARTIFACT art ON sa.ARTIFACT_ID = art.ARTIFACT_ID
WHERE d.DEPLOY_ID = 1
GROUP BY d.DEPLOY_ID, d.APPLICATION_NAME, d.STATUS;
