-- Get overall deployment statistics
SELECT 
    COUNT(*) AS TOTAL_DEPLOYMENTS,
    COUNT(CASE WHEN STATUS = 'SUCCESS' THEN 1 END) AS SUCCESSFUL,
    COUNT(CASE WHEN STATUS = 'FAILED' THEN 1 END) AS FAILED,
    COUNT(DISTINCT ENVIRONMENT_NAME) AS ENVIRONMENTS,
    MIN(DEPLOY_TIMESTAMP) AS FIRST_DEPLOYMENT,
    MAX(DEPLOY_TIMESTAMP) AS LAST_DEPLOYMENT
FROM DEPLOYZ.DEPLOY;
