-- Compare deployments across environments
SELECT 
    ENVIRONMENT_NAME,
    COUNT(*) AS TOTAL_DEPLOYMENTS,
    COUNT(CASE WHEN STATUS = 'SUCCESS' THEN 1 END) AS SUCCESSFUL,
    COUNT(CASE WHEN STATUS = 'FAILED' THEN 1 END) AS FAILED,
    ROUND(COUNT(CASE WHEN STATUS = 'SUCCESS' THEN 1 END) * 100.0 / COUNT(*), 2) AS SUCCESS_RATE
FROM DEPLOYZ.DEPLOY
GROUP BY ENVIRONMENT_NAME
ORDER BY ENVIRONMENT_NAME;
