-- Get all failed deployments with step counts
SELECT 
    d.DEPLOY_ID,
    d.EVIDENCE_NAME,
    d.ENVIRONMENT_NAME,
    d.DEPLOY_TIMESTAMP,
    d.STATUS,
    COUNT(DISTINCT s.STEP_ID) AS TOTAL_STEPS,
    COUNT(DISTINCT CASE WHEN s.STATUS = 'FAILED' THEN s.STEP_ID END) AS FAILED_STEPS
FROM DEPLOYZ.DEPLOY d
LEFT JOIN DEPLOYZ.ACTIVITY act ON d.DEPLOY_ID = act.DEPLOY_ID
LEFT JOIN DEPLOYZ.ACTION a ON act.ACTIVITY_ID = a.ACTIVITY_ID
LEFT JOIN DEPLOYZ.STEP s ON a.ACTION_ID = s.ACTION_ID
WHERE d.STATUS = 'FAILED'
GROUP BY d.DEPLOY_ID, d.EVIDENCE_NAME, d.ENVIRONMENT_NAME, d.DEPLOY_TIMESTAMP, d.STATUS
ORDER BY d.DEPLOY_TIMESTAMP DESC;
