-- Get deployments from last 7 days
SELECT 
    DEPLOY_ID,
    EVIDENCE_NAME,
    ENVIRONMENT_NAME,
    DEPLOY_TIMESTAMP,
    STATUS,
    ENGINE_VERSION
FROM DEPLOYZ.DEPLOY
WHERE DEPLOY_TIMESTAMP >= CURRENT_TIMESTAMP - 7 DAYS
ORDER BY DEPLOY_TIMESTAMP DESC;
