apiVersion: plum_py.ibm.com/v1
kind: ManifestState
metadata:
  name: GenAppCICS
  description: GenAppCICS
  version: 1.0.0
  annotations:
    creationTimestamp: 20230111.212152.556
    scm:
      type: git
      uri: git@github.com:jbyibm/cics-genapp.git
      branch: HEAD
      shortCommit: 64284b99
    package:
      name: sys-wazi-deploy-team/cics-genapp-plum-dynamic-build
      properties:
      - key: repository_path
        value: plum/dynamic
      - key: repository
        value: sys-wazi-deploy-team-pentest-generic-local
      - key: build_name
        value: sys-wazi-deploy-team/cics-genapp-plum-dynamic-build
      - key: build_number
        value: '22'
      uri: https://na.artifactory.swg-devops.com/ui/builds/sys-wazi-deploy-team%2Fcics-genapp-plum-dynamic-build/22
      type: ARTIFACTORY
    dbb:
      buildResultUri: https://zdevops-demo1.fyre.ibm.com:9443/dbb/rest/buildResult/49461
artifacts:
- name: LGICVS01
  description: LGICVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGICVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162122
  type: CICSLOAD
  hash: 0671b7202a52e86847c433cbeaf047f809969da15352bfe4a816b9bb8070f558
- name: LGICDB01
  description: LGICDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGICDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162135
  type: CICSLOAD
  hash: 08435a371f138f47185a41984818e59963149a31e9f72cb17f18ac97ed70174e
- name: LGDPDB01
  description: LGDPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.DBRM/LGDPDB01.DBRM
  - key: fingerprint
    value: 08ad956727bd8cd8bc2286b4854004ecb907313aaa89057d232754a7aaf5be2b
  type: DBRM
  hash: 08ad956727bd8cd8bc2286b4854004ecb907313aaa89057d232754a7aaf5be2b
- name: LGDPDB01
  description: LGDPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162120
  type: CICSLOAD
  hash: 157ed36740849f6168f268eaac77d9dcf6b9bd311382f1d26c2b0fdcc783cf35
- name: LGIPDB01
  description: LGIPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.DBRM/LGIPDB01.DBRM
  - key: fingerprint
    value: 1963fb2a0a9c20e5602e083819f44a18fae69e9853f7cebb16d9305b066b19c8
  type: DBRM
  hash: 1963fb2a0a9c20e5602e083819f44a18fae69e9853f7cebb16d9305b066b19c8
- name: LGDPVS01
  description: LGDPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162132
  type: CICSLOAD
  hash: 2389133b9ef4b9a8c10a87e2b56fe7e3aad7b0c1e305ad39e78cfd4920830f52
- name: LGAPDB01
  description: LGAPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162123
  type: CICSLOAD
  hash: 24f6efd6da873832928d78b8a6dee2efa003f7ec6a42769fbd93d4d6a16d7836
- name: LGUPDB01
  description: LGUPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.DBRM/LGUPDB01.DBRM
  - key: fingerprint
    value: 261e97ea881a9661940aa6a8c7c365c83cb165abaa8a5bd2767a7a56ddbfa568
  type: DBRM
  hash: 261e97ea881a9661940aa6a8c7c365c83cb165abaa8a5bd2767a7a56ddbfa568
- name: LGUCVS01
  description: LGUCVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162120
  type: CICSLOAD
  hash: 2f159484f4143aa5b13d12140cead1cca281136c25456fac1f040feaaaa1099f
- name: LGAPDB01
  description: LGAPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.DBRM/LGAPDB01.DBRM
  - key: fingerprint
    value: 35f25713aa766c078052f49f4067f85d0941b8bffc5e75fdd5d4890b6f6f29a9
  type: DBRM
  hash: 35f25713aa766c078052f49f4067f85d0941b8bffc5e75fdd5d4890b6f6f29a9
- name: LGACDB01
  description: LGACDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162138
  type: CICSLOAD
  hash: 3bf06da823491cf243b57fa600642760b5bde674ec67974eb4b3ce3ed8166272
- name: LGICDB01
  description: LGICDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.DBRM/LGICDB01.DBRM
  - key: fingerprint
    value: 436ce2a2c5878b2cf1b4c8eb873bb1e9174724d6e2faa8dbc021f64350fd5c4e
  type: DBRM
  hash: 436ce2a2c5878b2cf1b4c8eb873bb1e9174724d6e2faa8dbc021f64350fd5c4e
- name: LGACDB02
  description: LGACDB02.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB02.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162130
  type: CICSLOAD
  hash: 43fe70345adfb0b27d1309ca3ae9832d82878cb155e723835ddc804704302210
- name: LGACVS01
  description: LGACVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGACVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162126
  type: CICSLOAD
  hash: 5227711ae3d26f0ec69e7b3e59fc68adbe620b51117dea2bfd24c7202f948a00
- name: LGAPVS01
  description: LGAPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162136
  type: CICSLOAD
  hash: 5579f0837f0713c51519146ca32a3cee2d7059784e96c1b46bf08d735da5c026
- name: LGIPOL01
  description: LGIPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162130
  type: CICSLOAD
  hash: 584524fca2be58910c25d796c44213d00f40fd067a8e35b4576488590d792274
- name: LGACUS01
  description: LGACUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGACUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162125
  type: CICSLOAD
  hash: 615b2220bb834a77ac093cd66d078f2b94d4f8766e3f7b7e26fb96c98c78abe0
- name: LGSTSQ
  description: LGSTSQ.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGSTSQ.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162124
  type: CICSLOAD
  hash: 70c314f4784cda2f65b0a0ac07b168be279e66a0ad44355c7e621074a096b860
- name: HELLO1
  description: HELLO1.JCL
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.JCL/HELLO1.JCL
  - key: fingerprint
    value: 7178851f630501f1dde713b408e2d8ed2b4147638e5b818e8200851ed1a203b9
  type: JCL
  hash: 7178851f630501f1dde713b408e2d8ed2b4147638e5b818e8200851ed1a203b9
- name: LGUCDB01
  description: LGUCDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162131
  type: CICSLOAD
  hash: 75451d29f537af95d1796bc81dfefc67f7e621becb2e8f41ab2096da35b70be0
- name: LGAPOL01
  description: LGAPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162129
  type: CICSLOAD
  hash: 78235dbc60baec216634eefac0907327963278dbefde4c0d87149a6a11386d60
- name: SSMAP
  description: SSMAP.MAPLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/SSMAP.MAPLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162116
  type: MAPLOAD
  hash: 7ee5f0bba93f26a50db2fa6332ba1e9d0650b29a4b59c9e1afb273e60eb440f8
- name: LGACDB01
  description: LGACDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB01.DBRM
  - key: fingerprint
    value: 8538ffe62ce3579fb48b32064cee9dd9e994b3f2058a8b84b00f19f8de081ff5
  type: DBRM
  hash: 8538ffe62ce3579fb48b32064cee9dd9e994b3f2058a8b84b00f19f8de081ff5
- name: LGIPDB01
  description: LGIPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162127
  type: CICSLOAD
  hash: 8985cc3664050b6053c43d71ec8faafad1e0ce171ccddc42cfa0f1f209af7a4d
- name: LGUPDB01
  description: LGUPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162137
  type: CICSLOAD
  hash: 8b794f852864853d43aff487cad9dbf848302fe86f56e0d662938accb4323a5e
- name: LGSETUP
  description: LGSETUP.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGSETUP.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162134
  type: CICSLOAD
  hash: 920278e3ed9ab8cdf004f4cca017e6758e837182e8bbd42fcea2969b23b199c8
- name: LGUCUS01
  description: LGUCUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162118
  type: CICSLOAD
  hash: 962edca8db14fe60f06e990c075b56ab7fa063c4a177e43af9e8c95fe63fdc0d
- name: LGIPVS01
  description: LGIPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162139
  type: CICSLOAD
  hash: ac7820609fdee399c16d516909df1d950061f89d31261c91c6d77a84bf492248
- name: LGUPVS01
  description: LGUPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162128
  type: CICSLOAD
  hash: bb24db7a70dcaf232925a801090f7005206735c1e159eb0cf7ab5554f092ec7c
- name: LGICUS01
  description: LGICUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGICUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162119
  type: CICSLOAD
  hash: c7d4b07d6a5d59df587a8dda794fccf3e016093dc4ff4b4c8d21fbb3111b56ea
- name: LGDPOL01
  description: LGDPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162121
  type: CICSLOAD
  hash: caad7963051b17d5a5f83dae2dbe4a99a68836df02cb279a02989e931d58342c
- name: LGUPOL01
  description: LGUPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023011162133
  type: CICSLOAD
  hash: cf9ff079cb56a3fd8384529d039168cef7eb09daa820cec06ae884928a340520
- name: LGACDB02
  description: LGACDB02.DBRM
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB02.DBRM
  - key: fingerprint
    value: e69e35b834a120d3cc72903beb82b413b5edfd8083da6e6a9c0d167290bdb578
  type: DBRM
  hash: e69e35b834a120d3cc72903beb82b413b5edfd8083da6e6a9c0d167290bdb578
- name: LGUCDB01
  description: LGUCDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDDEPLOY.DBBBUILD.GENAPP.DBRM/LGUCDB01.DBRM
  - key: fingerprint
    value: ffd298eb576fe284f642aff9c3e464f3ba1d4febe7916c1f2bd0c6a6c935c128
  type: DBRM
  hash: ffd298eb576fe284f642aff9c3e464f3ba1d4febe7916c1f2bd0c6a6c935c128
