apiVersion: deploy.ibm.com/v1
kind: ManifestState
metadata:
  name: cics-genapp
  description: cics-genapp
  version: 1.0.536
  annotations:
    creation_timestamp: 20230405.072241.986
    scm:
      type: git
      uri: git@github.com:jbyibm/cics-genapp.git
      branch: main
      short_commit: f4e2c134
    package:
      name: sys-wazi-deploy-team/cics-genapp-plum-dynamic-build
      properties:
      - key: repository_path
        value: plum/dynamic/cics-genapp
      - key: repository
        value: sys-wazi-deploy-team-pentest-generic-local
      - key: build_name
        value: sys-wazi-deploy-team/cics-genapp-plum-dynamic-build
      - key: build_number
        value: '22'
      uri: https://na.artifactory.swg-devops.com/ui/builds/sys-wazi-deploy-team%2Fcics-genapp-plum-dynamic-build/22
      type: ARTIFACTORY
    dbb:
      build_result_uri: https://zdevops-demo1.fyre.ibm.com:9443/dbb/rest/buildResult/51904
artifacts:
- name: LGAPDB01
  description: LGAPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032125
  type: CICSLOAD
  hash: 020ea3e3d538410ee8f2d553b89edd6daa4e9ff497297fdb816fb7fdb37978c4
- name: LGICDB01
  description: LGICDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032138
  type: CICSLOAD
  hash: 034e7d4a861617ba5d1b9bb77dac4e75cb16995f257fe30c8e1e67bbb79ec0d5
- name: LGUPVS01
  description: LGUPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032130
  type: CICSLOAD
  hash: 10326078915662c90191e166deb9aa370f957da68341250650d438312b1c1fae
- name: LGICVS01
  description: LGICVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032124
  type: CICSLOAD
  hash: 1091983ff728effe16804b1b16b0c1f772e7fc527100a9e9c0df70c5a137e06b
- name: LGACUS01
  description: LGACUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032127
  type: CICSLOAD
  hash: 18f493a21d6879ab7491f500f72730895f0078952b00c0266ea49bfed0c94265
- name: LGAPOL01
  description: LGAPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032131
  type: CICSLOAD
  hash: 240707f3dabcf7bc967d592940e2ba28da894a7baa24aca1a1238b75b5eb24bb
- name: LGSETUP
  description: LGSETUP.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSETUP.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032137
  type: CICSLOAD
  hash: 25fae909f5c133ebaa656d470917128e1cd4d628967e65be9fa466da3b2a28a1
- name: LGUCDB01
  description: LGUCDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUCDB01.DBRM
  - key: fingerprint
    value: 273e91345122e7e0355b4806799ebe7980085308689bb2d20fffb66df51777df
  type: DBRM
  hash: 273e91345122e7e0355b4806799ebe7980085308689bb2d20fffb66df51777df
- name: HELLO2
  description: HELLO2.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO2.JCL
  - key: fingerprint
    value: 2a305ee5391a1f7f687177e712e9eb8d3747ff1992630b36438e3bbefc162488
  type: JCL
  hash: 2a305ee5391a1f7f687177e712e9eb8d3747ff1992630b36438e3bbefc162488
- name: LGACDB01
  description: LGACDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032141
  type: CICSLOAD
  hash: 2c1d7832c431a0bd632e84017e39acbd88b80adae349e9f85fb743392c043eea
- name: LGUCDB01
  description: LGUCDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032134
  type: CICSLOAD
  hash: 34c38a75d3ab01d04d80909181304deff9766d4caaed24b27e057617731da325
- name: SSMAP
  description: SSMAP.MAPLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/SSMAP.MAPLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032118
  type: MAPLOAD
  hash: 3efe0d95738aea948c05df033256f8fc2a4b2d6f58d25e05a489ca5dae4c47b8
- name: LGACDB02
  description: LGACDB02.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB02.DBRM
  - key: fingerprint
    value: 3feb99358f55436733637b8ec6cb8a35ffe2d9041bff1b02cbc3d73ee8f3cea1
  type: DBRM
  hash: 3feb99358f55436733637b8ec6cb8a35ffe2d9041bff1b02cbc3d73ee8f3cea1
- name: LGUPDB01
  description: LGUPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032140
  type: CICSLOAD
  hash: 6041a06acc42ba64e243d1881800b4f837bf86facce1bf797157cf6890464f71
- name: LGIPDB01
  description: LGIPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032129
  type: CICSLOAD
  hash: 6a5a7aa2d6bf92f1cca4604cc3f2a48cf30cc6f3453c68985c6b5b16756d7d05
- name: LGDPVS01
  description: LGDPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032135
  type: CICSLOAD
  hash: 6cbc779aaca210864437603bbaba1872b56e4bf7e43ead70c6e93b4b32337228
- name: LGACDB01
  description: LGACDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB01.DBRM
  - key: fingerprint
    value: 6f519bfeca95d39d68e555d66cd85154219daa1440a3c23956451b6151028d8f
  type: DBRM
  hash: 6f519bfeca95d39d68e555d66cd85154219daa1440a3c23956451b6151028d8f
- name: HELLO1
  description: HELLO1.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO1.JCL
  - key: fingerprint
    value: 7178851f630501f1dde713b408e2d8ed2b4147638e5b818e8200851ed1a203b9
  type: JCL
  hash: 7178851f630501f1dde713b408e2d8ed2b4147638e5b818e8200851ed1a203b9
- name: LGAPDB01
  description: LGAPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGAPDB01.DBRM
  - key: fingerprint
    value: 8096ebd9a97250868f3e68be6acd7aa94fe33a4813bc2120baeb193fadb29ac4
  type: DBRM
  hash: 8096ebd9a97250868f3e68be6acd7aa94fe33a4813bc2120baeb193fadb29ac4
- name: LGDPDB01
  description: LGDPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032122
  type: CICSLOAD
  hash: 848b494b236b2bb820b38fbdbcaa6e56bb8dcf2cb1cc1c3c6aa3b3951324a1c4
- name: LGACVS01
  description: LGACVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032128
  type: CICSLOAD
  hash: 8d402cf0ab1609f97922f2f41f2144f5ad6466810640cb13d0a53a5f6ceef911
- name: LGAPVS01
  description: LGAPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032139
  type: CICSLOAD
  hash: 943d0c3d587742bb8aab35e0d250e258129b25f8318886ebcab5f10cf6fb9ebf
- name: LGIPOL01
  description: LGIPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032132
  type: CICSLOAD
  hash: 9f079af5287f4699ae8373efa82fd6a7d4c67a40db20fb9b1349e76c74718921
- name: LGUPDB01
  description: LGUPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUPDB01.DBRM
  - key: fingerprint
    value: b1a1de56453db61880d33377ca5bbfd378c7bac536508c3a7943b5703a48fad9
  type: DBRM
  hash: b1a1de56453db61880d33377ca5bbfd378c7bac536508c3a7943b5703a48fad9
- name: LGIPVS01
  description: LGIPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032142
  type: CICSLOAD
  hash: b64e75f1b0ca74da495ba312a44696cf7c0156de8ab1d706a0bfc028d19c231b
- name: LGUCUS01
  description: LGUCUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032120
  type: CICSLOAD
  hash: c353b63656a00f8b7c7066d805b3b3f2c329add78ccfe5fff4f32ac708688a73
- name: LGDPOL01
  description: LGDPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032123
  type: CICSLOAD
  hash: c5007b9aefe5122bef98fc7cfac44ea664390e7fb9ab10c4c6a8707cfaa14f39
- name: LGIPDB01
  description: LGIPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGIPDB01.DBRM
  - key: fingerprint
    value: d9474f0be86de72a8310007c994576c13631e9a347907729aab2110154269d37
  type: DBRM
  hash: d9474f0be86de72a8310007c994576c13631e9a347907729aab2110154269d37
- name: LGUCVS01
  description: LGUCVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032122
  type: CICSLOAD
  hash: eb9d31578a79f38b38d4736ab00a6fcfc35e4b2b479eee812145b2e583470685
- name: LGDPDB01
  description: LGDPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGDPDB01.DBRM
  - key: fingerprint
    value: ebfd0b52cf7971047de506e12dbee4b9eedad4a811a7d16225cfbc222b8e7ec6
  type: DBRM
  hash: ebfd0b52cf7971047de506e12dbee4b9eedad4a811a7d16225cfbc222b8e7ec6
- name: LGACDB02
  description: LGACDB02.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB02.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032133
  type: CICSLOAD
  hash: f06c072edea2ce07be5115ed6f8575a82ea5385890826239925c54b97ca7af25
- name: LGUPOL01
  description: LGUPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032136
  type: CICSLOAD
  hash: f5b7fcff178d6efe2a39027fac4a115d9313c1c9d67a6c61a523bd55673f9331
- name: LGICDB01
  description: LGICDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGICDB01.DBRM
  - key: fingerprint
    value: fc71f645495302688a12fce6989ff3995d5afa8b7fd1596372938cc6c2c7e4ac
  type: DBRM
  hash: fc71f645495302688a12fce6989ff3995d5afa8b7fd1596372938cc6c2c7e4ac
- name: LGICUS01
  description: LGICUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032121
  type: CICSLOAD
  hash: fca9d80bc04d605aab86207358a2a2d99aac95e048087fae307b2ace30014d60
- name: LGSTSQ
  description: LGSTSQ.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSTSQ.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023095032126
  type: CICSLOAD
  hash: ff118b4016e792ba7dd72ee0fff8490fc61cb5f3de31d378598935155cc091af
