apiVersion: plum_py.ibm.com/v1
kind: ManifestState
metadata:
  name: GenAppCICS
  description: GenAppCICS
  version: 1.0.0
  annotations:
    creationTimestamp: 20230125.153229.633
    scm:
      type: git
      uri: git@github.com:jbyibm/cics-genapp.git
      branch: main
      shortCommit: d5996944
    package:
      name: sys-wazi-deploy-team/cics-genapp-plum-dynamic-build
      properties:
      - key: repository_path
        value: plum/dynamic
      - key: repository
        value: sys-wazi-deploy-team-pentest-generic-local
      - key: build_name
        value: sys-wazi-deploy-team/cics-genapp-plum-dynamic-build
      - key: build_number
        value: '22'
      uri: https://na.artifactory.swg-devops.com/ui/builds/sys-wazi-deploy-team%2Fcics-genapp-plum-dynamic-build/22
      type: ARTIFACTORY
    dbb:
      buildResultUri: https://zdevops-demo1.fyre.ibm.com:9443/dbb/rest/buildResult/50208
artifacts:
- name: LGACDB05
  description: LGACDB05.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB05.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023025024305
  type: CICSLOAD
  hash: 00610d296f0375ff2e23a34382e0fd06cc002529f0d8ae48718dd4719872c670
- name: LGDPDB01
  description: LGDPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGDPDB01.DBRM
  - key: fingerprint
    value: 0b49db21a35538653dad9112c1840f7e25590c0132ed9d3e92bfd9f7351e2ad1
  type: DBRM
  hash: 0b49db21a35538653dad9112c1840f7e25590c0132ed9d3e92bfd9f7351e2ad1
- name: LGUPDB01
  description: LGUPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163638
  type: CICSLOAD
  hash: 0f62564dca2a4f802eb77be3831aa36b462c3121b2a43d6221bafec999314fff
- name: LGACDB01
  description: LGACDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163639
  type: CICSLOAD
  hash: 113c6c6456de7ef0521ba30169a2091dba13c2848076a06a132acb634078c28b
- name: LGDPDB01
  description: LGDPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163623
  type: CICSLOAD
  hash: 1f3a00e3792d0af0a6f0d5819ba842def9c816061dcd86d6593c41c488945cf3
- name: LGACDB03
  description: LGACDB03.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB03.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023025103203
  type: CICSLOAD
  hash: 239bde1b6c819238d9ac9b3f5fc95cfe1eb8c504e98bfc566e77be1cbb89cba0
- name: LGSETUP
  description: LGSETUP.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSETUP.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163636
  type: CICSLOAD
  hash: 253e4739671ebc02a7d433442d43d7af1ab68201b529928447ddb89a9286b898
- name: LGAPOL01
  description: LGAPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163631
  type: CICSLOAD
  hash: 259207e9a29f90cf3fca6993d389a7555c6b13e53a46d463ff48b41afb983123
- name: LGACDB07
  description: LGACDB07.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB07.DBRM
  - key: fingerprint
    value: 281201cb677eb988eadb16a8f1bb88b2cd7101e02944bdbf5c888ba5157570a1
  type: DBRM
  hash: 281201cb677eb988eadb16a8f1bb88b2cd7101e02944bdbf5c888ba5157570a1
- name: LGACDB06
  description: LGACDB06.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB06.DBRM
  - key: fingerprint
    value: 28e28132872d06d18b0926c788edd01bbfade1a8f0db1fb86ebdf1c77bd51f56
  type: DBRM
  hash: 28e28132872d06d18b0926c788edd01bbfade1a8f0db1fb86ebdf1c77bd51f56
- name: HELLO2
  description: HELLO2.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO2.JCL
  - key: fingerprint
    value: 2a305ee5391a1f7f687177e712e9eb8d3747ff1992630b36438e3bbefc162488
  type: JCL
  hash: 2a305ee5391a1f7f687177e712e9eb8d3747ff1992630b36438e3bbefc162488
- name: LGACUS01
  description: LGACUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163627
  type: CICSLOAD
  hash: 2a474b24527c270802e7b9678cbfd2681ed47a214707c3c630d997d64bbcfa95
- name: SSMAP
  description: SSMAP.MAPLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/SSMAP.MAPLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163619
  type: MAPLOAD
  hash: 2d1334579ed1e096831977cfb3e61c83d1791da680b7989d96f70ea32d046323
- name: LGACDB02
  description: LGACDB02.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB02.DBRM
  - key: fingerprint
    value: 3dc9a3d74b586233fd5ec78c2bda94b80b4828a1d9c8cdf5b9e3b957d16501c1
  type: DBRM
  hash: 3dc9a3d74b586233fd5ec78c2bda94b80b4828a1d9c8cdf5b9e3b957d16501c1
- name: LGIPDB01
  description: LGIPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGIPDB01.DBRM
  - key: fingerprint
    value: 40d8aa2bbdd243ffea017fa821b13bddc0e6669a7208f4370c6c557cd3638bc1
  type: DBRM
  hash: 40d8aa2bbdd243ffea017fa821b13bddc0e6669a7208f4370c6c557cd3638bc1
- name: LGUPDB01
  description: LGUPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUPDB01.DBRM
  - key: fingerprint
    value: 42c27955b5cec34d6f210acb8fa73074d4e4ca1b0170ea364d802cdd9e21ba03
  type: DBRM
  hash: 42c27955b5cec34d6f210acb8fa73074d4e4ca1b0170ea364d802cdd9e21ba03
- name: LGSTSQ
  description: LGSTSQ.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGSTSQ.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163626
  type: CICSLOAD
  hash: 47f5aaa8cbc71f58d9320493de19ef7014899cde5b07098ab115a6fd036be6be
- name: LGUPOL01
  description: LGUPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163635
  type: CICSLOAD
  hash: 4955ceadbeaba621a796464a95ed2ad85c635a888a8bd3c7e6ceb90295cb2ac9
- name: LGICVS01
  description: LGICVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163625
  type: CICSLOAD
  hash: 4c949c5294a7ee80438d1264861e376c37f63652afff63d1ff0e36eae05c2413
- name: LGDPOL01
  description: LGDPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163624
  type: CICSLOAD
  hash: 5421e410ac1448e032fdb22cada1cf460c270a7776d9e6755de7cf4198e6e199
- name: LGUPVS01
  description: LGUPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163630
  type: CICSLOAD
  hash: 5819e859dba5a04987bc71e1ac0bb7a56c145af7832749d3c2c3384892a8cb9d
- name: LGACDB01
  description: LGACDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB01.DBRM
  - key: fingerprint
    value: 5a2cd0283beb30f966f6ba67845de11148bbc1e9df7d47cefd4c7b569612e749
  type: DBRM
  hash: 5a2cd0283beb30f966f6ba67845de11148bbc1e9df7d47cefd4c7b569612e749
- name: LGIPVS01
  description: LGIPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163640
  type: CICSLOAD
  hash: 6d9a1ea2742056cb4822534c98f5b31ef6b1bffc39cbb20510f326b5716c3aaf
- name: HELLO1
  description: HELLO1.JCL
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.JCL/HELLO1.JCL
  - key: fingerprint
    value: 7178851f630501f1dde713b408e2d8ed2b4147638e5b818e8200851ed1a203b9
  type: JCL
  hash: 7178851f630501f1dde713b408e2d8ed2b4147638e5b818e8200851ed1a203b9
- name: LGUCVS01
  description: LGUCVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163622
  type: CICSLOAD
  hash: 7a8fbb340463cb07e9538d1dbde748145e4794f2ec5d5911deeae7eb770852f8
- name: LGDPVS01
  description: LGDPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGDPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163634
  type: CICSLOAD
  hash: 7c9687a2287da441db04be9bcb8106a936d5edd01e7dad97acb5b01bde0fe983
- name: LGUCUS01
  description: LGUCUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163620
  type: CICSLOAD
  hash: 81c4e4642a024c876a3cb95633fa735923b43de5b8f0aa6bb16a57ac51dc4ce8
- name: LGAPDB01
  description: LGAPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163625
  type: CICSLOAD
  hash: 8645249aaaba94b8f17c09f6ea9dcb92f60a65262db0ecea5ec12be1d5b7645c
- name: LGIPDB01
  description: LGIPDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163629
  type: CICSLOAD
  hash: 8759d37265495329181fbf529a2d87760d0feb386643168fe900b1ddcb293d09
- name: LGICDB01
  description: LGICDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGICDB01.DBRM
  - key: fingerprint
    value: 89d8f2c7c22201236cabcf783a58f168aa96100a2483784740e90db3e40b8296
  type: DBRM
  hash: 89d8f2c7c22201236cabcf783a58f168aa96100a2483784740e90db3e40b8296
- name: LGIPOL01
  description: LGIPOL01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGIPOL01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163631
  type: CICSLOAD
  hash: 8cb6796d08c0ea69dc3eb1ceb586a98c72b53758beb889cd3da9352da7f048cb
- name: LGACDB06
  description: LGACDB06.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB06.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023025024304
  type: CICSLOAD
  hash: 9150dbbf5d45934630d654cc603a1abbd9d6c2b9faada959c19a187596e6c4a4
- name: LGAPVS01
  description: LGAPVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGAPVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163637
  type: CICSLOAD
  hash: 9aeb15132a487a04f09d70738822031056b8fa058278b95bdccab43ef99b81a7
- name: LGACDB02
  description: LGACDB02.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB02.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163632
  type: CICSLOAD
  hash: add2304c544d033e982cd06c1ca25575459edfdd609f891b8e828d5a7dea88a4
- name: LGICDB01
  description: LGICDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163636
  type: CICSLOAD
  hash: b96c0bb1bdc17d752ef0abfe8c821261aea95ae97b649279029b2e986e74efae
- name: LGAPDB01
  description: LGAPDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGAPDB01.DBRM
  - key: fingerprint
    value: c3e54f7587df2da5d9aba460a40fbd66435dba22d3099f37bae9db68aad200f8
  type: DBRM
  hash: c3e54f7587df2da5d9aba460a40fbd66435dba22d3099f37bae9db68aad200f8
- name: LGUCDB01
  description: LGUCDB01.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGUCDB01.DBRM
  - key: fingerprint
    value: c41991cd84de40d37a995e5881223ad88fc8b41004d755b7ff160a38625c37c4
  type: DBRM
  hash: c41991cd84de40d37a995e5881223ad88fc8b41004d755b7ff160a38625c37c4
- name: LGUCDB01
  description: LGUCDB01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGUCDB01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163633
  type: CICSLOAD
  hash: c8bb824165d08bd773150f73119f5914cb4e38b86fc41a92fb1fd27d07db6b3b
- name: LGICUS01
  description: LGICUS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGICUS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163621
  type: CICSLOAD
  hash: cda0c390abcfe05dee1da75111411ca0c5548f700f05549d71eb9d2fb73c7495
- name: LGACDB03
  description: LGACDB03.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB03.DBRM
  - key: fingerprint
    value: d392d2e186b0ee1b4731cba48a1b8e0dde1cb792eea3dab4aa315eb356510aec
  type: DBRM
  hash: d392d2e186b0ee1b4731cba48a1b8e0dde1cb792eea3dab4aa315eb356510aec
- name: LGACDB04
  description: LGACDB04.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB04.DBRM
  - key: fingerprint
    value: d5fc16e83d94798b2471d43769001f20fa6f47b4c85265438e15b2a720215766
  type: DBRM
  hash: d5fc16e83d94798b2471d43769001f20fa6f47b4c85265438e15b2a720215766
- name: LGACDB05
  description: LGACDB05.DBRM
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.DBRM/LGACDB05.DBRM
  - key: fingerprint
    value: df8e501675946fbcb68f6dceb46741a46cdb849e47314a2a9283f86ce308fe8d
  type: DBRM
  hash: df8e501675946fbcb68f6dceb46741a46cdb849e47314a2a9283f86ce308fe8d
- name: LGACVS01
  description: LGACVS01.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACVS01.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023024163628
  type: CICSLOAD
  hash: ea79cf836aebb5a6d232592b094e345e7cf5d7b550dec8bee3cc69b5538de032
- name: LGACDB07
  description: LGACDB07.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB07.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023025024302
  type: CICSLOAD
  hash: ec63132fd0eadf3fc16cdef7e7b1b38c0c24e1b82818545cc4c9525e1d58410a
- name: LGACDB04
  description: LGACDB04.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB04.CICSLOAD
  - key: fingerprint
    value: 5695PMB01 02042023025091310
  type: CICSLOAD
  hash: f53141de70475f9905c0db86bd172c02e435a430dbac54c648259bc4076a6de2
