#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
all:
  hosts:
    ZOS_SIT:
      ansible_host: 9.30.222.103
      ansible_user: JENKINS
      ansible_ssh_port: 222
      
    ZOS_UAT:
      ansible_host: 9.30.222.103
      ansible_user: JENKINS
      ansible_ssh_port: 222
      
    ZOS_PROD:
      ansible_host: 9.30.222.103
      ansible_user: JENKINS
      ansible_ssh_port: 222